In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('/content/tech_advertising_campaigns_dataset.csv')

In [16]:
df.head()

,campaign_id,campaign_objective,platform,ad_placement,device_type,operating_system,creative_format,creative_size,ad_copy_length,has_call_to_action,...,avg_session_duration_seconds,pages_per_session,industry_vertical,budget_tier,CTR,CPC,conversion_rate,CPA,ROAS,profit
0,CAMP_00001,Lead Generation,Facebook,Search,Mobile,Android,Text,728x90,Short,False,...,70,2.00,E-commerce,High,0.606,2.23,0.498,448.23,0.32,-606.79
1,CAMP_00002,Engagement,Facebook,Feed,Mobile,iOS,Image,320x50,Long,True,...,105,2.74,Finance,Medium,0.932,2.48,1.071,231.63,1.49,570.04
2,CAMP_00003,Conversions,Google Ads,Feed,Tablet,iOS,Video,1920x1080,Short,False,...,149,3.97,Healthcare,Low,1.033,3.88,5.357,72.43,6.68,2468.70
3,CAMP_00004,Conversions,LinkedIn,Search,Desktop,iOS,Carousel,1920x1080,Short,False,...,147,2.49,Education,Medium,1.573,8.29,2.439,339.89,0.49,-517.39
4,CAMP_00005,Brand Awareness,Facebook,Stories,Mobile,iOS,Image,1920x1080,Short,False,...,81,3.04,SaaS,Low,1.409,1.41,0.000,0.00,0.00,-425.82

In [17]:
df.shape

(10000, 41)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  object
 1   campaign_objective            10000 non-null  object
 2   platform                      10000 non-null  object
 3   ad_placement                  10000 non-null  object
 4   device_type                   10000 non-null  object
 5   operating_system              10000 non-null  object
 6   creative_format               10000 non-null  object
 7   creative_size                 10000 non-null  object
 8   ad_copy_length                10000 non-null  object
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  object
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  object
 13  target_audience_gender        10000 non-null  object
 14  audience_interest_category    10000 non-null  object
 15  income_bracket                10000 non-null  object
 16  purchase_intent_score         10000 non-null  object
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  object
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  object
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  object
 34  budget_tier                   10000 non-null  object
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
dtypes: bool(2), float64(11), int64(9), object(19)
memory usage: 3.0+ MB

In [19]:
df.isnull().sum()

campaign_id                     0
campaign_objective              0
platform                        0
ad_placement                    0
device_type                     0
operating_system                0
creative_format                 0
creative_size                   0
ad_copy_length                  0
has_call_to_action              0
creative_emotion                0
creative_age_days               0
target_audience_age             0
target_audience_gender          0
audience_interest_category      0
income_bracket                  0
purchase_intent_score           0
retargeting_flag                0
start_date                      0
quarter                         0
day_of_week                     0
hour_of_day                     0
campaign_day                    0
quality_score                   0
actual_cpc                      0
impressions                     0
clicks                          0
conversions                     0
ad_spend                        0
revenue                         0
bounce_rate                     0
avg_session_duration_seconds    0
pages_per_session               0
industry_vertical               0
budget_tier                     0
CTR                             0
CPC                             0
conversion_rate                 0
CPA                             0
ROAS                            0
profit                          0
dtype: int64

In [20]:
# Find rows containing at least one empty/blank cell
df[df.astype(str).apply(lambda x: x.str.strip() == '').any(axis=1)]

Empty DataFrame
Columns: [campaign_id, campaign_objective, platform, ad_placement, device_type, operating_system, creative_format, creative_size, ad_copy_length, has_call_to_action, creative_emotion, creative_age_days, target_audience_age, target_audience_gender, audience_interest_category, income_bracket, purchase_intent_score, retargeting_flag, start_date, quarter, day_of_week, hour_of_day, campaign_day, quality_score, actual_cpc, impressions, clicks, conversions, ad_spend, revenue, bounce_rate, avg_session_duration_seconds, pages_per_session, industry_vertical, budget_tier, CTR, CPC, conversion_rate, CPA, ROAS, profit]
Index: []

[0 rows x 41 columns]

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
# Convert start_date from text to datetime
df['start_date'] = pd.to_datetime(df['start_date'])

In [23]:
# Verify whether the provided CTR matches our own calculation
df['CTR_Check'] = (df['clicks'] / df['impressions']) * 100

# Compare the provided CTR with our calculated CTR
(df[['CTR', 'CTR_Check']].head(10)).round(3)

     CTR  CTR_Check
0  0.606      0.606
1  0.932      0.932
2  1.033      1.033
3  1.573      1.573
4  1.409      1.409
5  1.229      1.229
6  3.359      3.359
7  1.441      1.441
8  0.998      0.998
9  2.345      2.345

In [24]:
# Calculate profit margin only when revenue is greater than zero
df['profit_margin'] = np.where(
    df['revenue'] > 0,
    (df['profit'] / df['revenue']) * 100,
    np.nan
)

# Check the profit margin results
df[['revenue', 'profit', 'profit_margin']].head()

   revenue   profit  profit_margin
0   289.67  -606.79    -209.476301
1  1728.20   570.04      32.984608
2  2903.26  2468.70      85.031999
3   502.28  -517.39    -103.008282
4     0.00  -425.82            NaN

In [25]:
# Check how many campaigns have zero revenue
(df['revenue'] == 0).sum()

np.int64(594)

In [26]:
# Remove the temporary CTR verification variable
df.drop(columns=['CTR_Check'], inplace=True)

# Check the final dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 42 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   campaign_id                   10000 non-null  object
 1   campaign_objective            10000 non-null  object
 2   platform                      10000 non-null  object
 3   ad_placement                  10000 non-null  object
 4   device_type                   10000 non-null  object
 5   operating_system              10000 non-null  object
 6   creative_format               10000 non-null  object
 7   creative_size                 10000 non-null  object
 8   ad_copy_length                10000 non-null  object
 9   has_call_to_action            10000 non-null  bool
 10  creative_emotion              10000 non-null  object
 11  creative_age_days             10000 non-null  int64
 12  target_audience_age           10000 non-null  object
 13  target_audience_gender        10000 non-null  object
 14  audience_interest_category    10000 non-null  object
 15  income_bracket                10000 non-null  object
 16  purchase_intent_score         10000 non-null  object
 17  retargeting_flag              10000 non-null  bool
 18  start_date                    10000 non-null  datetime64[ns]
 19  quarter                       10000 non-null  int64
 20  day_of_week                   10000 non-null  object
 21  hour_of_day                   10000 non-null  int64
 22  campaign_day                  10000 non-null  int64
 23  quality_score                 10000 non-null  int64
 24  actual_cpc                    10000 non-null  float64
 25  impressions                   10000 non-null  int64
 26  clicks                        10000 non-null  int64
 27  conversions                   10000 non-null  int64
 28  ad_spend                      10000 non-null  float64
 29  revenue                       10000 non-null  float64
 30  bounce_rate                   10000 non-null  float64
 31  avg_session_duration_seconds  10000 non-null  int64
 32  pages_per_session             10000 non-null  float64
 33  industry_vertical             10000 non-null  object
 34  budget_tier                   10000 non-null  object
 35  CTR                           10000 non-null  float64
 36  CPC                           10000 non-null  float64
 37  conversion_rate               10000 non-null  float64
 38  CPA                           10000 non-null  float64
 39  ROAS                          10000 non-null  float64
 40  profit                        10000 non-null  float64
 41  profit_margin                 9406 non-null   float64
dtypes: bool(2), datetime64[ns](1), float64(12), int64(9), object(18)
memory usage: 3.1+ MB

In [27]:
# Export the cleaned dataset for Tableau
df.to_csv('cleaned_digital_advertising_campaigns.csv', index=False)

# Download the cleaned dataset
from google.colab import files
files.download('cleaned_digital_advertising_campaigns.csv')