In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Import Original 4 Datasets (Provider, Beneficiary, Inpatient and Outpatient)
provider = pd.read_csv("Provider.csv")
beneficiary = pd.read_csv("Beneficiary.csv")
inpatient = pd.read_csv("Inpatient.csv")
outpatient = pd.read_csv("Outpatient.csv")

In [ ]:
#Data Exploration
print("Provider:", provider.shape)
print("Beneficiary:", beneficiary.shape)
print("Inpatient:", inpatient.shape)
print("Outpatient:", outpatient.shape)

Provider: (5410, 2)
Beneficiary: (138556, 25)
Inpatient: (40474, 30)
Outpatient: (517737, 27)

In [ ]:
#header description
provider.head()

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No
3  PRV51005            Yes
4  PRV51007             No

In [ ]:
beneficiary.head()

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaN,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaN,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaN,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200

In [ ]:
inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
outpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947

In [ ]:
#Identifying Relationship between the tables across the 4 datasets
provider.columns.tolist()

['Provider', 'PotentialFraud']

In [ ]:
beneficiary.columns.tolist()

['BeneID',
 'DOB',
 'DOD',
 'Gender',
 'Race',
 'RenalDiseaseIndicator',
 'State',
 'County',
 'NoOfMonths_PartACov',
 'NoOfMonths_PartBCov',
 'ChronicCond_Alzheimer',
 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease',
 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'IPAnnualReimbursementAmt',
 'IPAnnualDeductibleAmt',
 'OPAnnualReimbursementAmt',
 'OPAnnualDeductibleAmt']

In [ ]:
inpatient.columns.tolist()

['BeneID',
 'ClaimID',
 'ClaimStartDt',
 'ClaimEndDt',
 'Provider',
 'InscClaimAmtReimbursed',
 'AttendingPhysician',
 'OperatingPhysician',
 'OtherPhysician',
 'AdmissionDt',
 'ClmAdmitDiagnosisCode',
 'DeductibleAmtPaid',
 'DischargeDt',
 'DiagnosisGroupCode',
 'ClmDiagnosisCode_1',
 'ClmDiagnosisCode_2',
 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4',
 'ClmDiagnosisCode_5',
 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7',
 'ClmDiagnosisCode_8',
 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10',
 'ClmProcedureCode_1',
 'ClmProcedureCode_2',
 'ClmProcedureCode_3',
 'ClmProcedureCode_4',
 'ClmProcedureCode_5',
 'ClmProcedureCode_6']

In [ ]:
outpatient.columns.tolist()

['BeneID',
 'ClaimID',
 'ClaimStartDt',
 'ClaimEndDt',
 'Provider',
 'InscClaimAmtReimbursed',
 'AttendingPhysician',
 'OperatingPhysician',
 'OtherPhysician',
 'ClmDiagnosisCode_1',
 'ClmDiagnosisCode_2',
 'ClmDiagnosisCode_3',
 'ClmDiagnosisCode_4',
 'ClmDiagnosisCode_5',
 'ClmDiagnosisCode_6',
 'ClmDiagnosisCode_7',
 'ClmDiagnosisCode_8',
 'ClmDiagnosisCode_9',
 'ClmDiagnosisCode_10',
 'ClmProcedureCode_1',
 'ClmProcedureCode_2',
 'ClmProcedureCode_3',
 'ClmProcedureCode_4',
 'ClmProcedureCode_5',
 'ClmProcedureCode_6',
 'DeductibleAmtPaid',
 'ClmAdmitDiagnosisCode']

In [ ]:
#Identifying the datatypes
provider.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provider        5410 non-null   object
 1   PotentialFraud  5410 non-null   object
dtypes: object(2)
memory usage: 84.7+ KB

In [ ]:
beneficiary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138556 entries, 0 to 138555
Data columns (total 25 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   BeneID                           138556 non-null  object
 1   DOB                              138556 non-null  object
 2   DOD                              1421 non-null    object
 3   Gender                           138556 non-null  int64
 4   Race                             138556 non-null  int64
 5   RenalDiseaseIndicator            138556 non-null  object
 6   State                            138556 non-null  int64
 7   County                           138556 non-null  int64
 8   NoOfMonths_PartACov              138556 non-null  int64
 9   NoOfMonths_PartBCov              138556 non-null  int64
 10  ChronicCond_Alzheimer            138556 non-null  int64
 11  ChronicCond_Heartfailure         138556 non-null  int64
 12  ChronicCond_KidneyDisease        138556 non-null  int64
 13  ChronicCond_Cancer               138556 non-null  int64
 14  ChronicCond_ObstrPulmonary       138556 non-null  int64
 15  ChronicCond_Depression           138556 non-null  int64
 16  ChronicCond_Diabetes             138556 non-null  int64
 17  ChronicCond_IschemicHeart        138556 non-null  int64
 18  ChronicCond_Osteoporasis         138556 non-null  int64
 19  ChronicCond_rheumatoidarthritis  138556 non-null  int64
 20  ChronicCond_stroke               138556 non-null  int64
 21  IPAnnualReimbursementAmt         138556 non-null  int64
 22  IPAnnualDeductibleAmt            138556 non-null  int64
 23  OPAnnualReimbursementAmt         138556 non-null  int64
 24  OPAnnualDeductibleAmt            138556 non-null  int64
dtypes: int64(21), object(4)
memory usage: 26.4+ MB

In [ ]:
inpatient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40474 entries, 0 to 40473
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BeneID                  40474 non-null  object
 1   ClaimID                 40474 non-null  object
 2   ClaimStartDt            40474 non-null  object
 3   ClaimEndDt              40474 non-null  object
 4   Provider                40474 non-null  object
 5   InscClaimAmtReimbursed  40474 non-null  int64
 6   AttendingPhysician      40362 non-null  object
 7   OperatingPhysician      23830 non-null  object
 8   OtherPhysician          4690 non-null   object
 9   AdmissionDt             40474 non-null  object
 10  ClmAdmitDiagnosisCode   40474 non-null  object
 11  DeductibleAmtPaid       39575 non-null  float64
 12  DischargeDt             40474 non-null  object
 13  DiagnosisGroupCode      40474 non-null  object
 14  ClmDiagnosisCode_1      40474 non-null  object
 15  ClmDiagnosisCode_2      40248 non-null  object
 16  ClmDiagnosisCode_3      39798 non-null  object
 17  ClmDiagnosisCode_4      38940 non-null  object
 18  ClmDiagnosisCode_5      37580 non-null  object
 19  ClmDiagnosisCode_6      35636 non-null  object
 20  ClmDiagnosisCode_7      33216 non-null  object
 21  ClmDiagnosisCode_8      30532 non-null  object
 22  ClmDiagnosisCode_9      26977 non-null  object
 23  ClmDiagnosisCode_10     3927 non-null   object
 24  ClmProcedureCode_1      23148 non-null  float64
 25  ClmProcedureCode_2      5454 non-null   float64
 26  ClmProcedureCode_3      965 non-null    float64
 27  ClmProcedureCode_4      116 non-null    float64
 28  ClmProcedureCode_5      9 non-null      float64
 29  ClmProcedureCode_6      0 non-null      float64
dtypes: float64(7), int64(1), object(22)
memory usage: 9.3+ MB

In [ ]:
outpatient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517737 entries, 0 to 517736
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   BeneID                  517737 non-null  object
 1   ClaimID                 517737 non-null  object
 2   ClaimStartDt            517737 non-null  object
 3   ClaimEndDt              517737 non-null  object
 4   Provider                517737 non-null  object
 5   InscClaimAmtReimbursed  517737 non-null  int64
 6   AttendingPhysician      516341 non-null  object
 7   OperatingPhysician      90617 non-null   object
 8   OtherPhysician          195046 non-null  object
 9   ClmDiagnosisCode_1      507284 non-null  object
 10  ClmDiagnosisCode_2      322357 non-null  object
 11  ClmDiagnosisCode_3      203257 non-null  object
 12  ClmDiagnosisCode_4      125596 non-null  object
 13  ClmDiagnosisCode_5      74344 non-null   object
 14  ClmDiagnosisCode_6      48756 non-null   object
 15  ClmDiagnosisCode_7      32961 non-null   object
 16  ClmDiagnosisCode_8      22912 non-null   object
 17  ClmDiagnosisCode_9      14838 non-null   object
 18  ClmDiagnosisCode_10     1083 non-null    object
 19  ClmProcedureCode_1      162 non-null     float64
 20  ClmProcedureCode_2      36 non-null      float64
 21  ClmProcedureCode_3      4 non-null       float64
 22  ClmProcedureCode_4      2 non-null       float64
 23  ClmProcedureCode_5      0 non-null       float64
 24  ClmProcedureCode_6      0 non-null       float64
 25  DeductibleAmtPaid       517737 non-null  int64
 26  ClmAdmitDiagnosisCode   105425 non-null  object
dtypes: float64(6), int64(2), object(19)
memory usage: 106.7+ MB

In [ ]:
provider.isnull().sum()

Provider          0
PotentialFraud    0
dtype: int64

In [ ]:
beneficiary.isnull().sum()

BeneID                                  0
DOB                                     0
DOD                                137135
Gender                                  0
Race                                    0
RenalDiseaseIndicator                   0
State                                   0
County                                  0
NoOfMonths_PartACov                     0
NoOfMonths_PartBCov                     0
ChronicCond_Alzheimer                   0
ChronicCond_Heartfailure                0
ChronicCond_KidneyDisease               0
ChronicCond_Cancer                      0
ChronicCond_ObstrPulmonary              0
ChronicCond_Depression                  0
ChronicCond_Diabetes                    0
ChronicCond_IschemicHeart               0
ChronicCond_Osteoporasis                0
ChronicCond_rheumatoidarthritis         0
ChronicCond_stroke                      0
IPAnnualReimbursementAmt                0
IPAnnualDeductibleAmt                   0
OPAnnualReimbursementAmt                0
OPAnnualDeductibleAmt                   0
dtype: int64

In [ ]:
inpatient.isnull().sum()

BeneID                        0
ClaimID                       0
ClaimStartDt                  0
ClaimEndDt                    0
Provider                      0
InscClaimAmtReimbursed        0
AttendingPhysician          112
OperatingPhysician        16644
OtherPhysician            35784
AdmissionDt                   0
ClmAdmitDiagnosisCode         0
DeductibleAmtPaid           899
DischargeDt                   0
DiagnosisGroupCode            0
ClmDiagnosisCode_1            0
ClmDiagnosisCode_2          226
ClmDiagnosisCode_3          676
ClmDiagnosisCode_4         1534
ClmDiagnosisCode_5         2894
ClmDiagnosisCode_6         4838
ClmDiagnosisCode_7         7258
ClmDiagnosisCode_8         9942
ClmDiagnosisCode_9        13497
ClmDiagnosisCode_10       36547
ClmProcedureCode_1        17326
ClmProcedureCode_2        35020
ClmProcedureCode_3        39509
ClmProcedureCode_4        40358
ClmProcedureCode_5        40465
ClmProcedureCode_6        40474
dtype: int64

In [ ]:
outpatient.isnull().sum()

BeneID                         0
ClaimID                        0
ClaimStartDt                   0
ClaimEndDt                     0
Provider                       0
InscClaimAmtReimbursed         0
AttendingPhysician          1396
OperatingPhysician        427120
OtherPhysician            322691
ClmDiagnosisCode_1         10453
ClmDiagnosisCode_2        195380
ClmDiagnosisCode_3        314480
ClmDiagnosisCode_4        392141
ClmDiagnosisCode_5        443393
ClmDiagnosisCode_6        468981
ClmDiagnosisCode_7        484776
ClmDiagnosisCode_8        494825
ClmDiagnosisCode_9        502899
ClmDiagnosisCode_10       516654
ClmProcedureCode_1        517575
ClmProcedureCode_2        517701
ClmProcedureCode_3        517733
ClmProcedureCode_4        517735
ClmProcedureCode_5        517737
ClmProcedureCode_6        517737
DeductibleAmtPaid              0
ClmAdmitDiagnosisCode     412312
dtype: int64

# 4.3 Feature Engineering

4.3.1 Theme 1 – Provider Operational Behaviour
Feature 1 – Total Inpatient Claims

In [ ]:
# Engineer Feature 1: Calculate the total number of inpatient claims submitted by each healthcare provider.

inpatient[['Provider', 'ClaimID']].head(10)

   Provider   ClaimID
0  PRV55912  CLM46614
1  PRV55907  CLM66048
2  PRV56046  CLM68358
3  PRV52405  CLM38412
4  PRV56614  CLM63689
5  PRV54986  CLM70950
6  PRV54090  CLM32075
7  PRV51148  CLM62376
8  PRV55839  CLM62784
9  PRV55215  CLM31519

In [ ]:
# Calculate the total number of inpatient claims submitted by each healthcare provider.

total_inpatient_claims = (
    inpatient
    .groupby('Provider')['ClaimID']
    .count()
    .reset_index(name='Total_Inpatient_Claims')
)

In [ ]:
# Preview the engineered Total_Inpatient_Claims feature.

total_inpatient_claims.head()

   Provider  Total_Inpatient_Claims
0  PRV51001                       5
1  PRV51003                      62
2  PRV51007                       3
3  PRV51008                       2
4  PRV51011                       1

In [ ]:
# Verify the number of providers after aggregating inpatient claims.

print(total_inpatient_claims.shape)

(2092, 2)

# ============================================================
# Feature 2 – Total Outpatient Claims
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and ClaimID columns used to calculate total outpatient claims.

outpatient[['Provider', 'ClaimID']].head(10)

   Provider    ClaimID
0  PRV56011  CLM624349
1  PRV57610  CLM189947
2  PRV57595  CLM438021
3  PRV56011  CLM121801
4  PRV56011  CLM150998
5  PRV56011  CLM173224
6  PRV56011  CLM224741
7  PRV56011  CLM252512
8  PRV56011  CLM322683
9  PRV56011  CLM339500

In [ ]:
# Engineer Feature 2: Calculate the total number of outpatient claims submitted by each healthcare provider.

total_outpatient_claims = (
    outpatient
    .groupby('Provider')['ClaimID']
    .count()
    .reset_index(name='Total_Outpatient_Claims')
)

In [ ]:
# Preview the engineered Total_Outpatient_Claims feature.

total_outpatient_claims.head()

   Provider  Total_Outpatient_Claims
0  PRV51001                       20
1  PRV51003                       70
2  PRV51004                      149
3  PRV51005                     1165
4  PRV51007                       69

In [ ]:
# Verify the number of providers after aggregating outpatient claims.

print(total_outpatient_claims.shape)

(5012, 2)

# ============================================================
# Feature 3 – Total Claims
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the first few records of the inpatient and outpatient claim features before calculating total claims.

total_inpatient_claims.head()

   Provider  Total_Inpatient_Claims
0  PRV51001                       5
1  PRV51003                      62
2  PRV51007                       3
3  PRV51008                       2
4  PRV51011                       1

In [ ]:
total_outpatient_claims.head()

   Provider  Total_Outpatient_Claims
0  PRV51001                       20
1  PRV51003                       70
2  PRV51004                      149
3  PRV51005                     1165
4  PRV51007                       69

In [ ]:
# Merge the inpatient and outpatient claim counts temporarily to calculate total claims.

total_claims_temp = pd.merge(
    total_inpatient_claims,
    total_outpatient_claims,
    on='Provider',
    how='outer'
)

In [ ]:
# Replace missing claim counts with zero for providers without inpatient or outpatient claims.

total_claims_temp[['Total_Inpatient_Claims', 'Total_Outpatient_Claims']] = (
    total_claims_temp[['Total_Inpatient_Claims', 'Total_Outpatient_Claims']]
    .fillna(0)
)

In [ ]:
# Engineer Feature 3: Calculate the total number of claims submitted by each healthcare provider.

total_claims_temp['Total_Claims'] = (
    total_claims_temp['Total_Inpatient_Claims'] +
    total_claims_temp['Total_Outpatient_Claims']
)

In [ ]:
# Keep only the Provider and engineered Total_Claims feature for later merging.

total_claims = total_claims_temp[['Provider', 'Total_Claims']]

In [ ]:
# Preview the engineered Total_Claims feature.

total_claims.head()

   Provider  Total_Claims
0  PRV51001          25.0
1  PRV51003         132.0
2  PRV51004         149.0
3  PRV51005        1165.0
4  PRV51007          72.0

In [ ]:
# Verify the number of providers after calculating total claims.

print(total_claims.shape)

(5410, 2)

# ============================================================
# Feature 4 – Number of Unique Beneficiaries
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and BeneID columns from inpatient and outpatient claims used to identify unique beneficiaries.

inpatient[['Provider', 'BeneID']].head(10)

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014
5  PRV54986  BENE11017
6  PRV54090  BENE11018
7  PRV51148  BENE11028
8  PRV55839  BENE11031
9  PRV55215  BENE11034

In [ ]:
outpatient[['Provider', 'BeneID']].head(10)

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004
5  PRV56011  BENE11004
6  PRV56011  BENE11004
7  PRV56011  BENE11004
8  PRV56011  BENE11004
9  PRV56011  BENE11004

In [ ]:
# Combine inpatient and outpatient Provider-BeneID records before counting unique beneficiaries.

beneficiary_claims_temp = pd.concat(
    [
        inpatient[['Provider', 'BeneID']],
        outpatient[['Provider', 'BeneID']]
    ],
    ignore_index=True
)

In [ ]:
# Engineer Feature 4: Calculate the number of unique beneficiaries treated by each healthcare provider.

unique_beneficiaries = (
    beneficiary_claims_temp
    .groupby('Provider')['BeneID']
    .nunique()
    .reset_index(name='Unique_Beneficiaries')
)

In [ ]:
# Preview the engineered Unique_Beneficiaries feature.

unique_beneficiaries.head()

   Provider  Unique_Beneficiaries
0  PRV51001                    24
1  PRV51003                   117
2  PRV51004                   138
3  PRV51005                   495
4  PRV51007                    58

In [ ]:
# Verify the number of providers after calculating the number of unique beneficiaries.

print(unique_beneficiaries.shape)

(5410, 2)

Merge First 4 features into Theme 1

In [ ]:
# Merge the first four Theme 1 claim activity features using Provider as the common key.

theme1_features = (
    total_inpatient_claims
    .merge(total_outpatient_claims, on='Provider', how='outer')
    .merge(total_claims, on='Provider', how='outer')
    .merge(unique_beneficiaries, on='Provider', how='outer')
)

In [ ]:
# Replace missing claim activity values with zero for providers without a specific claim type.

theme1_features = theme1_features.fillna(0)

In [ ]:
# Preview the Theme 1 feature dataset after combining the first four engineered features.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries
0,PRV51001,5.0,20.0,25.0,24
1,PRV51003,62.0,70.0,132.0,117
2,PRV51004,0.0,149.0,149.0,138
3,PRV51005,0.0,1165.0,1165.0,495
4,PRV51007,3.0,69.0,72.0,58

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 5)

# ============================================================
# Feature 5 – Average Inpatient Reimbursement
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and reimbursement amount columns used to calculate the average inpatient reimbursement.

inpatient[['Provider', 'InscClaimAmtReimbursed']].head(10)

   Provider  InscClaimAmtReimbursed
0  PRV55912                   26000
1  PRV55907                    5000
2  PRV56046                    5000
3  PRV52405                    5000
4  PRV56614                   10000
5  PRV54986                    8000
6  PRV54090                    8000
7  PRV51148                    6000
8  PRV55839                    7000
9  PRV55215                   29000

In [ ]:
# Engineer Feature 5: Calculate the average inpatient reimbursement amount for each healthcare provider.

avg_inpatient_reimbursement = (
    inpatient
    .groupby('Provider')['InscClaimAmtReimbursed']
    .mean()
    .reset_index(name='Avg_Inpatient_Reimbursement')
)

In [ ]:
# Preview the engineered Avg_Inpatient_Reimbursement feature.

avg_inpatient_reimbursement.head()

   Provider  Avg_Inpatient_Reimbursement
0  PRV51001                 19400.000000
1  PRV51003                  9241.935484
2  PRV51007                  6333.333333
3  PRV51008                 12500.000000
4  PRV51011                  5000.000000

In [ ]:
# Verify the number of providers after calculating the average inpatient reimbursement.

print(avg_inpatient_reimbursement.shape)

(2092, 2)

In [ ]:
# Merge the Avg_Inpatient_Reimbursement feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    avg_inpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing average inpatient reimbursement values with zero for providers without inpatient claims.

theme1_features['Avg_Inpatient_Reimbursement'] = (
    theme1_features['Avg_Inpatient_Reimbursement']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Avg_Inpatient_Reimbursement.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement
0,PRV51001,5.0,20.0,25.0,24,19400.000000
1,PRV51003,62.0,70.0,132.0,117,9241.935484
2,PRV51004,0.0,149.0,149.0,138,0.000000
3,PRV51005,0.0,1165.0,1165.0,495,0.000000
4,PRV51007,3.0,69.0,72.0,58,6333.333333

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 6)

# ============================================================
# Feature 6 – Average Outpatient Reimbursement
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and reimbursement amount columns used to calculate the average outpatient reimbursement.

outpatient[['Provider', 'InscClaimAmtReimbursed']].head(10)

   Provider  InscClaimAmtReimbursed
0  PRV56011                      30
1  PRV57610                      80
2  PRV57595                      10
3  PRV56011                      40
4  PRV56011                     200
5  PRV56011                      20
6  PRV56011                      40
7  PRV56011                     200
8  PRV56011                      60
9  PRV56011                     500

In [ ]:
# Engineer Feature 6: Calculate the average outpatient reimbursement amount for each healthcare provider.

avg_outpatient_reimbursement = (
    outpatient
    .groupby('Provider')['InscClaimAmtReimbursed']
    .mean()
    .reset_index(name='Avg_Outpatient_Reimbursement')
)

In [ ]:
# Preview the engineered Avg_Outpatient_Reimbursement feature.

avg_outpatient_reimbursement.head()

   Provider  Avg_Outpatient_Reimbursement
0  PRV51001                    382.000000
1  PRV51003                    466.714286
2  PRV51004                    350.134228
3  PRV51005                    241.124464
4  PRV51007                    213.188406

In [ ]:
# Verify the number of providers after calculating the average outpatient reimbursement.

print(avg_outpatient_reimbursement.shape)

(5012, 2)

In [ ]:
# Merge the Avg_Outpatient_Reimbursement feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    avg_outpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing average outpatient reimbursement values with zero for providers without outpatient claims.

theme1_features['Avg_Outpatient_Reimbursement'] = (
    theme1_features['Avg_Outpatient_Reimbursement']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Avg_Outpatient_Reimbursement.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 7)

# ============================================================
# Feature 7 – Total Inpatient Reimbursement
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and reimbursement amount columns used to calculate the total inpatient reimbursement.

inpatient[['Provider', 'InscClaimAmtReimbursed']].head(10)

   Provider  InscClaimAmtReimbursed
0  PRV55912                   26000
1  PRV55907                    5000
2  PRV56046                    5000
3  PRV52405                    5000
4  PRV56614                   10000
5  PRV54986                    8000
6  PRV54090                    8000
7  PRV51148                    6000
8  PRV55839                    7000
9  PRV55215                   29000

In [ ]:
# Engineer Feature 7: Calculate the total inpatient reimbursement amount for each healthcare provider.

total_inpatient_reimbursement = (
    inpatient
    .groupby('Provider')['InscClaimAmtReimbursed']
    .sum()
    .reset_index(name='Total_Inpatient_Reimbursement')
)

In [ ]:
# Preview the engineered Total_Inpatient_Reimbursement feature.

total_inpatient_reimbursement.head()

   Provider  Total_Inpatient_Reimbursement
0  PRV51001                          97000
1  PRV51003                         573000
2  PRV51007                          19000
3  PRV51008                          25000
4  PRV51011                           5000

In [ ]:
# Verify the number of providers after calculating the total inpatient reimbursement.

print(total_inpatient_reimbursement.shape)

(2092, 2)

In [ ]:
# Merge the Total_Inpatient_Reimbursement feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    total_inpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing total inpatient reimbursement values with zero for providers without inpatient claims.

theme1_features['Total_Inpatient_Reimbursement'] = (
    theme1_features['Total_Inpatient_Reimbursement']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Total_Inpatient_Reimbursement.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 8)

# ============================================================
# Feature 8 – Total Outpatient Reimbursement
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and reimbursement amount columns used to calculate the total outpatient reimbursement.

outpatient[['Provider', 'InscClaimAmtReimbursed']].head(10)

   Provider  InscClaimAmtReimbursed
0  PRV56011                      30
1  PRV57610                      80
2  PRV57595                      10
3  PRV56011                      40
4  PRV56011                     200
5  PRV56011                      20
6  PRV56011                      40
7  PRV56011                     200
8  PRV56011                      60
9  PRV56011                     500

In [ ]:
# Engineer Feature 8: Calculate the total outpatient reimbursement amount for each healthcare provider.

total_outpatient_reimbursement = (
    outpatient
    .groupby('Provider')['InscClaimAmtReimbursed']
    .sum()
    .reset_index(name='Total_Outpatient_Reimbursement')
)

In [ ]:
# Preview the engineered Total_Outpatient_Reimbursement feature.

total_outpatient_reimbursement.head()

   Provider  Total_Outpatient_Reimbursement
0  PRV51001                            7640
1  PRV51003                           32670
2  PRV51004                           52170
3  PRV51005                          280910
4  PRV51007                           14710

In [ ]:
# Verify the number of providers after calculating the total outpatient reimbursement.

print(total_outpatient_reimbursement.shape)

(5012, 2)

In [ ]:
# Merge the Total_Outpatient_Reimbursement feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    total_outpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing total outpatient reimbursement values with zero for providers without outpatient claims.

theme1_features['Total_Outpatient_Reimbursement'] = (
    theme1_features['Total_Outpatient_Reimbursement']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Total_Outpatient_Reimbursement.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 9)

# ============================================================
# Feature 9 – Average Claim Duration
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the claim start and end dates used to calculate claim duration.

inpatient[['Provider', 'ClaimStartDt', 'ClaimEndDt']].head(10)

   Provider ClaimStartDt  ClaimEndDt
0  PRV55912   2009-04-12  2009-04-18
1  PRV55907   2009-08-31  2009-09-02
2  PRV56046   2009-09-17  2009-09-20
3  PRV52405   2009-02-14  2009-02-22
4  PRV56614   2009-08-13  2009-08-30
5  PRV54986   2009-10-06  2009-10-12
6  PRV54090   2009-01-02  2009-01-07
7  PRV51148   2009-08-03  2009-08-07
8  PRV55839   2009-08-06  2009-08-09
9  PRV55215   2008-12-29  2009-01-05

In [ ]:
# Convert claim start and end dates into datetime format.

inpatient['ClaimStartDt'] = pd.to_datetime(inpatient['ClaimStartDt'])
inpatient['ClaimEndDt'] = pd.to_datetime(inpatient['ClaimEndDt'])

In [ ]:
# Calculate the duration of each inpatient claim in days.

inpatient['Claim_Duration'] = (inpatient['ClaimEndDt'] - inpatient['ClaimStartDt']).dt.days

In [ ]:
# Preview the calculated claim duration for each inpatient claim.

inpatient[['Provider',
           'ClaimStartDt',
           'ClaimEndDt',
           'Claim_Duration']].head()

   Provider ClaimStartDt ClaimEndDt  Claim_Duration
0  PRV55912   2009-04-12 2009-04-18               6
1  PRV55907   2009-08-31 2009-09-02               2
2  PRV56046   2009-09-17 2009-09-20               3
3  PRV52405   2009-02-14 2009-02-22               8
4  PRV56614   2009-08-13 2009-08-30              17

In [ ]:
# Engineer Feature 9: Calculate the average claim duration for each healthcare provider.

avg_claim_duration = (
    inpatient
    .groupby('Provider')['Claim_Duration']
    .mean()
    .reset_index(name='Avg_Claim_Duration')
)

In [ ]:
# Preview the engineered Avg_Claim_Duration feature.

avg_claim_duration.head()

   Provider  Avg_Claim_Duration
0  PRV51001            5.000000
1  PRV51003            5.161290
2  PRV51007            5.333333
3  PRV51008            4.000000
4  PRV51011            5.000000

In [ ]:
# Verify the number of providers after calculating the average claim duration.

print(avg_claim_duration.shape)

(2092, 2)

In [ ]:
# Merge the Avg_Claim_Duration feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    avg_claim_duration,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing average claim duration values with zero for providers without inpatient claims.

theme1_features['Avg_Claim_Duration'] = (
    theme1_features['Avg_Claim_Duration']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Avg_Claim_Duration.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 10)

Extra Check on Outpatient

In [ ]:
# Convert outpatient claim start and end dates into datetime format.

outpatient['ClaimStartDt'] = pd.to_datetime(outpatient['ClaimStartDt'])
outpatient['ClaimEndDt'] = pd.to_datetime(outpatient['ClaimEndDt'])

In [ ]:
# Calculate the duration of each outpatient claim in days.

outpatient['Claim_Duration'] = (
    outpatient['ClaimEndDt'] -
    outpatient['ClaimStartDt']
).dt.days

In [ ]:
# Display the frequency distribution of outpatient claim duration.

outpatient['Claim_Duration'].value_counts().sort_index()

Claim_Duration
0     453348
1      11960
2       4366
3       2597
4       2238
5       1511
6       1306
7       2564
8       1189
9       1378
10       982
11       953
12       903
13       947
14      2735
15       975
16      1136
17       808
18       800
19       727
20     24312
21         1
23         1
Name: count, dtype: int64

In [ ]:
# Display summary statistics for outpatient claim duration.

outpatient['Claim_Duration'].describe()

count    517737.000000
mean          1.420532
std           4.707387
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max          23.000000
Name: Claim_Duration, dtype: float64

In [ ]:
# Preview outpatient claim durations.

outpatient[['ClaimStartDt',
             'ClaimEndDt',
             'Claim_Duration']].head(20)

   ClaimStartDt ClaimEndDt  Claim_Duration
0    2009-10-11 2009-10-11               0
1    2009-02-12 2009-02-12               0
2    2009-06-27 2009-06-27               0
3    2009-01-06 2009-01-06               0
4    2009-01-22 2009-01-22               0
5    2009-02-03 2009-02-03               0
6    2009-03-03 2009-03-03               0
7    2009-03-18 2009-03-18               0
8    2009-04-25 2009-05-15              20
9    2009-05-04 2009-05-16              12
10   2009-08-17 2009-08-17               0
11   2009-09-06 2009-09-06               0
12   2009-10-13 2009-10-13               0
13   2009-12-09 2009-12-09               0
14   2009-12-22 2009-12-22               0
15   2009-01-31 2009-01-31               0
16   2009-02-02 2009-02-02               0
17   2009-02-12 2009-02-12               0
18   2009-03-19 2009-03-19               0
19   2009-04-02 2009-04-02               0

# ============================================================
# Feature 10 – Average Length of Stay
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the admission and discharge dates used to calculate length of hospital stay.

inpatient[['Provider', 'AdmissionDt', 'DischargeDt']].head(10)

   Provider AdmissionDt DischargeDt
0  PRV55912  2009-04-12  2009-04-18
1  PRV55907  2009-08-31  2009-09-02
2  PRV56046  2009-09-17  2009-09-20
3  PRV52405  2009-02-14  2009-02-22
4  PRV56614  2009-08-13  2009-08-30
5  PRV54986  2009-10-06  2009-10-12
6  PRV54090  2009-01-02  2009-01-07
7  PRV51148  2009-08-03  2009-08-07
8  PRV55839  2009-08-06  2009-08-09
9  PRV55215  2008-12-29  2009-01-05

In [ ]:
# Convert admission and discharge dates into datetime format.

inpatient['AdmissionDt'] = pd.to_datetime(inpatient['AdmissionDt'])
inpatient['DischargeDt'] = pd.to_datetime(inpatient['DischargeDt'])

In [ ]:
# Calculate the length of hospital stay for each inpatient claim.

inpatient['Length_of_Stay'] = ( inpatient['DischargeDt'] - inpatient['AdmissionDt']).dt.days

In [ ]:
# Preview the calculated length of stay.

inpatient[['Provider',
            'AdmissionDt',
            'DischargeDt',
            'Length_of_Stay']].head(10)

   Provider AdmissionDt DischargeDt  Length_of_Stay
0  PRV55912  2009-04-12  2009-04-18               6
1  PRV55907  2009-08-31  2009-09-02               2
2  PRV56046  2009-09-17  2009-09-20               3
3  PRV52405  2009-02-14  2009-02-22               8
4  PRV56614  2009-08-13  2009-08-30              17
5  PRV54986  2009-10-06  2009-10-12               6
6  PRV54090  2009-01-02  2009-01-07               5
7  PRV51148  2009-08-03  2009-08-07               4
8  PRV55839  2009-08-06  2009-08-09               3
9  PRV55215  2008-12-29  2009-01-05               7

In [ ]:
# Engineer Feature 10: Calculate the average length of hospital stay for each healthcare provider.

avg_length_of_stay = (
    inpatient
    .groupby('Provider')['Length_of_Stay']
    .mean()
    .reset_index(name='Avg_Length_of_Stay')
)

In [ ]:
# Preview the engineered Avg_Length_of_Stay feature.

avg_length_of_stay.head()

   Provider  Avg_Length_of_Stay
0  PRV51001            5.000000
1  PRV51003            5.161290
2  PRV51007            5.333333
3  PRV51008            4.000000
4  PRV51011            5.000000

In [ ]:
# Verify the number of providers after calculating average length of stay.

print(avg_length_of_stay.shape)

(2092, 2)

In [ ]:
# Merge the Avg_Length_of_Stay feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    avg_length_of_stay,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing average length of stay values with zero for providers without inpatient claims.

theme1_features['Avg_Length_of_Stay'] = (
    theme1_features['Avg_Length_of_Stay']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Avg_Length_of_Stay.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration,Avg_Length_of_Stay
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000,5.000000
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290,5.161290
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000,0.000000
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000,0.000000
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333,5.333333

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 11)

# ============================================================
# Feature 11 – Inpatient-to-Outpatient Ratio
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the inpatient and outpatient claim counts used to calculate the claim ratio.

theme1_features[['Provider',
                 'Total_Inpatient_Claims',
                 'Total_Outpatient_Claims']].head()

   Provider  Total_Inpatient_Claims  Total_Outpatient_Claims
0  PRV51001                     5.0                     20.0
1  PRV51003                    62.0                     70.0
2  PRV51004                     0.0                    149.0
3  PRV51005                     0.0                   1165.0
4  PRV51007                     3.0                     69.0

In [ ]:
# Engineer Feature 11: Calculate the inpatient-to-outpatient claim ratio for each healthcare provider.

theme1_features['Inpatient_Outpatient_Ratio'] = (
    theme1_features['Total_Inpatient_Claims'] /
    theme1_features['Total_Outpatient_Claims'].replace(0, 1)
)

In [ ]:
# Preview the engineered Inpatient_Outpatient_Ratio feature.

theme1_features[['Provider',
                 'Inpatient_Outpatient_Ratio']].head()

   Provider  Inpatient_Outpatient_Ratio
0  PRV51001                    0.250000
1  PRV51003                    0.885714
2  PRV51004                    0.000000
3  PRV51005                    0.000000
4  PRV51007                    0.043478

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 12)

# ============================================================
# Feature 12 – Number of States Served
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and BeneID columns used to link providers with beneficiaries.

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
beneficiary[['BeneID', 'State']].head()

      BeneID  State
0  BENE11001     39
1  BENE11002     39
2  BENE11003     52
3  BENE11004     39
4  BENE11005     24

In [ ]:
# Combine inpatient and outpatient provider-beneficiary records.

provider_bene = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Remove duplicate provider-beneficiary pairs.

provider_bene = provider_bene.drop_duplicates()

In [ ]:
# Merge beneficiary state information with provider-beneficiary records.

provider_bene = provider_bene.merge(
    beneficiary[['BeneID', 'State']],
    on='BeneID',
    how='left'
)

In [ ]:
# Engineer Feature 12: Calculate the number of unique states served by each healthcare provider.

states_served = (
    provider_bene
    .groupby('Provider')['State']
    .nunique()
    .reset_index(name='Number_of_States_Served')
)

In [ ]:
# Preview the engineered Number_of_States_Served feature.

states_served.head()

   Provider  Number_of_States_Served
0  PRV51001                        1
1  PRV51003                        3
2  PRV51004                        9
3  PRV51005                        4
4  PRV51007                        2

In [ ]:
# Merge the Number_of_States_Served feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    states_served,
    on='Provider',
    how='left'
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Number_of_States_Served.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration,Avg_Length_of_Stay,Inpatient_Outpatient_Ratio,Number_of_States_Served
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000,5.000000,0.250000,1
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290,5.161290,0.885714,3
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000,0.000000,0.000000,9
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000,0.000000,0.000000,4
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333,5.333333,0.043478,2

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 13)

# ============================================================
# Feature 13 – Number of Counties Served
# Theme 1 – Provider Claim Behaviour
# ============================================================

In [ ]:
# Display the Provider and BeneID columns used to link providers with beneficiaries.

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
beneficiary[['BeneID', 'County']].head()

      BeneID  County
0  BENE11001     230
1  BENE11002     280
2  BENE11003     590
3  BENE11004     270
4  BENE11005     680

In [ ]:
# Combine inpatient and outpatient provider-beneficiary records.

provider_bene = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Remove duplicate provider-beneficiary pairs.

provider_bene = provider_bene.drop_duplicates()

In [ ]:
# Merge beneficiary county information with provider-beneficiary records.

provider_bene = provider_bene.merge(
    beneficiary[['BeneID', 'County']],
    on='BeneID',
    how='left'
)

In [ ]:
# Engineer Feature 13: Calculate the number of unique counties served by each healthcare provider.

counties_served = (
    provider_bene
    .groupby('Provider')['County']
    .nunique()
    .reset_index(name='Number_of_Counties_Served')
)

In [ ]:
# Preview the engineered Number_of_Counties_Served feature.

counties_served.head()

   Provider  Number_of_Counties_Served
0  PRV51001                          7
1  PRV51003                         23
2  PRV51004                         28
3  PRV51005                         26
4  PRV51007                          6

In [ ]:
# Merge the Number_of_Counties_Served feature into the Theme 1 feature dataset.

theme1_features = theme1_features.merge(
    counties_served,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero for providers without beneficiary county information.

theme1_features['Number_of_Counties_Served'] = (
    theme1_features['Number_of_Counties_Served']
    .fillna(0)
)

In [ ]:
# Preview the Theme 1 feature dataset after adding Number_of_Counties_Served.

theme1_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration,Avg_Length_of_Stay,Inpatient_Outpatient_Ratio,Number_of_States_Served,Number_of_Counties_Served
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000,5.000000,0.250000,1,7
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290,5.161290,0.885714,3,23
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000,0.000000,0.000000,9,28
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000,0.000000,0.000000,4,26
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333,5.333333,0.043478,2,6

In [ ]:
# Verify the dimensions of the Theme 1 feature dataset.

print(theme1_features.shape)

(5410, 14)

# ============================================================
# Feature 14: Average Patient Age
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 14

beneficiary[['BeneID', 'DOB']].head()

      BeneID         DOB
0  BENE11001  1943-01-01
1  BENE11002  1936-09-01
2  BENE11003  1936-08-01
3  BENE11004  1922-07-01
4  BENE11005  1935-09-01

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Convert beneficiary date of birth into datetime format

beneficiary['DOB'] = pd.to_datetime(beneficiary['DOB'])

In [ ]:
# Calculate beneficiary age

reference_date = pd.Timestamp('2009-12-31')

beneficiary['Age'] = (
    (reference_date - beneficiary['DOB']).dt.days // 365
)

In [ ]:
# Merge beneficiary age into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'Age']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate average patient age for each provider

average_patient_age = (
    provider_bene_temp
    .groupby('Provider')['Age']
    .mean()
    .reset_index()
)

average_patient_age.rename(
    columns={'Age': 'AveragePatientAge'},
    inplace=True
)

In [ ]:
# Preview engineered feature

average_patient_age.head()

   Provider  AveragePatientAge
0  PRV51001          78.208333
1  PRV51003          69.051282
2  PRV51004          72.557971
3  PRV51005          70.070707
4  PRV51007          68.017241

In [ ]:
# Verify engineered feature structure

average_patient_age.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Provider           5410 non-null   object
 1   AveragePatientAge  5410 non-null   float64
dtypes: float64(1), object(1)
memory usage: 84.7+ KB

In [ ]:
# Check for missing values

average_patient_age.isnull().sum()

Provider             0
AveragePatientAge    0
dtype: int64

In [ ]:
# Create Theme 2 dataset using the first engineered feature

theme2_features = average_patient_age.copy()

In [ ]:
theme2_features['AveragePatientAge'] = (
    theme2_features['AveragePatientAge']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

   Provider  AveragePatientAge
0  PRV51001          78.208333
1  PRV51003          69.051282
2  PRV51004          72.557971
3  PRV51005          70.070707
4  PRV51007          68.017241

In [ ]:
# Verify Theme 2 dataset

theme2_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Provider           5410 non-null   object
 1   AveragePatientAge  5410 non-null   float64
dtypes: float64(1), object(1)
memory usage: 84.7+ KB

In [ ]:
# Confirm one row per provider

theme2_features['Provider'].nunique(), len(theme2_features)

(5410, 5410)

# ============================================================
# Feature 15: Percentage Male Patients
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 15

beneficiary[['BeneID', 'Gender']].head()

      BeneID  Gender
0  BENE11001       1
1  BENE11002       2
2  BENE11003       1
3  BENE11004       1
4  BENE11005       1

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge beneficiary gender into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'Gender']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of male patients for each provider

percentage_male_patients = (
    provider_bene_temp
    .groupby('Provider')['Gender']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

percentage_male_patients.rename(
    columns={'Gender': 'PercentageMalePatients'},
    inplace=True
)

In [ ]:
# Preview engineered feature

percentage_male_patients.head()

   Provider  PercentageMalePatients
0  PRV51001               37.500000
1  PRV51003               41.880342
2  PRV51004               32.608696
3  PRV51005               42.020202
4  PRV51007               46.551724

In [ ]:
# Check for missing values

percentage_male_patients.isnull().sum()

Provider                  0
PercentageMalePatients    0
dtype: int64

In [ ]:
# Verify one row per provider

percentage_male_patients.shape

(5410, 2)

In [ ]:
# Merge Feature 15 into Theme 2 dataset

theme2_features = theme2_features.merge(
    percentage_male_patients,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['PercentageMalePatients'] = (
    theme2_features['PercentageMalePatients']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

   Provider  AveragePatientAge  PercentageMalePatients
0  PRV51001          78.208333               37.500000
1  PRV51003          69.051282               41.880342
2  PRV51004          72.557971               32.608696
3  PRV51005          70.070707               42.020202
4  PRV51007          68.017241               46.551724

# ============================================================
# Feature 16: Percentage Female Patients
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 16

beneficiary[['BeneID', 'Gender']].head()

      BeneID  Gender
0  BENE11001       1
1  BENE11002       2
2  BENE11003       1
3  BENE11004       1
4  BENE11005       1

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge beneficiary gender into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'Gender']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of female patients for each provider

percentage_female_patients = (
    provider_bene_temp
    .groupby('Provider')['Gender']
    .apply(lambda x: (x == 2).mean() * 100)
    .reset_index()
)

percentage_female_patients.rename(
    columns={'Gender': 'PercentageFemalePatients'},
    inplace=True
)

In [ ]:
# Preview engineered feature

percentage_female_patients.head()

   Provider  PercentageFemalePatients
0  PRV51001                 62.500000
1  PRV51003                 58.119658
2  PRV51004                 67.391304
3  PRV51005                 57.979798
4  PRV51007                 53.448276

In [ ]:
# Verify engineered feature structure

percentage_female_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Provider                  5410 non-null   object
 1   PercentageFemalePatients  5410 non-null   float64
dtypes: float64(1), object(1)
memory usage: 84.7+ KB

In [ ]:
# Check for missing values

percentage_female_patients.isnull().sum()

Provider                    0
PercentageFemalePatients    0
dtype: int64

In [ ]:
# Verify one row per provider

percentage_female_patients.shape

(5410, 2)

In [ ]:
# Merge Feature 16 into Theme 2 dataset

theme2_features = theme2_features.merge(
    percentage_female_patients,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['PercentageFemalePatients'] = (
    theme2_features['PercentageFemalePatients']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients
0,PRV51001,78.208333,37.500000,62.500000
1,PRV51003,69.051282,41.880342,58.119658
2,PRV51004,72.557971,32.608696,67.391304
3,PRV51005,70.070707,42.020202,57.979798
4,PRV51007,68.017241,46.551724,53.448276

# ============================================================
# Feature 17: Average Part A Coverage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 17

beneficiary[['BeneID', 'NoOfMonths_PartACov']].head()

      BeneID  NoOfMonths_PartACov
0  BENE11001                   12
1  BENE11002                   12
2  BENE11003                   12
3  BENE11004                   12
4  BENE11005                   12

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Part A coverage into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'NoOfMonths_PartACov']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average Part A coverage for each provider

average_part_a_coverage = (
    provider_bene_temp
    .groupby('Provider')['NoOfMonths_PartACov']
    .mean()
    .reset_index()
)

average_part_a_coverage.rename(
    columns={'NoOfMonths_PartACov': 'AveragePartACoverage'},
    inplace=True
)

In [ ]:
# Preview engineered feature

average_part_a_coverage.head()

   Provider  AveragePartACoverage
0  PRV51001             12.000000
1  PRV51003             11.794872
2  PRV51004             11.855072
3  PRV51005             11.830303
4  PRV51007             11.793103

In [ ]:
# Check for missing values

average_part_a_coverage.isnull().sum()

Provider                0
AveragePartACoverage    0
dtype: int64

In [ ]:
# Verify one row per provider

average_part_a_coverage.shape

(5410, 2)

In [ ]:
# Merge Feature 17 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_part_a_coverage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AveragePartACoverage'] = (
    theme2_features['AveragePartACoverage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage
0,PRV51001,78.208333,37.500000,62.500000,12.000000
1,PRV51003,69.051282,41.880342,58.119658,11.794872
2,PRV51004,72.557971,32.608696,67.391304,11.855072
3,PRV51005,70.070707,42.020202,57.979798,11.830303
4,PRV51007,68.017241,46.551724,53.448276,11.793103

# ============================================================
# Feature 18: Average Part B Coverage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 18

beneficiary[['BeneID', 'NoOfMonths_PartBCov']].head()

      BeneID  NoOfMonths_PartBCov
0  BENE11001                   12
1  BENE11002                   12
2  BENE11003                   12
3  BENE11004                   12
4  BENE11005                   12

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Part B coverage into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'NoOfMonths_PartBCov']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average Part B coverage for each provider

average_part_b_coverage = (
    provider_bene_temp
    .groupby('Provider')['NoOfMonths_PartBCov']
    .mean()
    .reset_index()
)

average_part_b_coverage.rename(
    columns={'NoOfMonths_PartBCov': 'AveragePartBCoverage'},
    inplace=True
)

In [ ]:
# Preview engineered feature

average_part_b_coverage.head()

   Provider  AveragePartBCoverage
0  PRV51001             12.000000
1  PRV51003             11.854701
2  PRV51004             11.956522
3  PRV51005             11.886869
4  PRV51007             11.793103

In [ ]:
# Check for missing values

average_part_b_coverage.isnull().sum()

Provider                0
AveragePartBCoverage    0
dtype: int64

In [ ]:
# Verify one row per provider

average_part_b_coverage.shape

(5410, 2)

In [ ]:
# Merge Feature 18 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_part_b_coverage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AveragePartBCoverage'] = (
    theme2_features['AveragePartBCoverage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103

# ============================================================
# Feature 19: Alzheimer Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 19

beneficiary[['BeneID', 'ChronicCond_Alzheimer']].head()

      BeneID  ChronicCond_Alzheimer
0  BENE11001                      1
1  BENE11002                      2
2  BENE11003                      1
3  BENE11004                      1
4  BENE11005                      2

In [ ]:
# Check the coding of the Alzheimer chronic condition variable

beneficiary['ChronicCond_Alzheimer'].value_counts()

ChronicCond_Alzheimer
2    92530
1    46026
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Alzheimer condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Alzheimer']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Alzheimer patients for each provider

alzheimer_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Alzheimer']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

alzheimer_patient_percentage.rename(
    columns={'ChronicCond_Alzheimer': 'AlzheimerPatientPercentage'},
    inplace=True
)

In [ ]:
# Preview engineered feature

alzheimer_patient_percentage.head()

   Provider  AlzheimerPatientPercentage
0  PRV51001                   58.333333
1  PRV51003                   37.606838
2  PRV51004                   43.478261
3  PRV51005                   33.333333
4  PRV51007                   36.206897

In [ ]:
# Check for missing values

alzheimer_patient_percentage.isnull().sum()

Provider                      0
AlzheimerPatientPercentage    0
dtype: int64

In [ ]:
# Verify one row per provider

alzheimer_patient_percentage.shape

(5410, 2)

In [ ]:
# Merge Feature 19 into Theme 2 dataset

theme2_features = theme2_features.merge(
    alzheimer_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AlzheimerPatientPercentage'] = (
    theme2_features['AlzheimerPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897

# ============================================================
# Feature 20: Heart Failure Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 20

beneficiary[['BeneID', 'ChronicCond_Heartfailure']].head()

      BeneID  ChronicCond_Heartfailure
0  BENE11001                         2
1  BENE11002                         2
2  BENE11003                         2
3  BENE11004                         1
4  BENE11005                         2

In [ ]:
# Check the coding of the Heart Failure chronic condition variable

beneficiary['ChronicCond_Heartfailure'].value_counts()

ChronicCond_Heartfailure
2    70154
1    68402
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Heart Failure condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Heartfailure']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Heart Failure patients for each provider

heart_failure_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Heartfailure']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

heart_failure_patient_percentage.rename(
    columns={'ChronicCond_Heartfailure': 'HeartFailurePatientPercentage'},
    inplace=True
)

In [ ]:
# Preview engineered feature

heart_failure_patient_percentage.head()

   Provider  HeartFailurePatientPercentage
0  PRV51001                      75.000000
1  PRV51003                      59.829060
2  PRV51004                      59.420290
3  PRV51005                      53.131313
4  PRV51007                      51.724138

In [ ]:
# Check for missing values

heart_failure_patient_percentage.isnull().sum()

Provider                         0
HeartFailurePatientPercentage    0
dtype: int64

In [ ]:
# Merge Feature 20 into Theme 2 dataset

theme2_features = theme2_features.merge(
    heart_failure_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['HeartFailurePatientPercentage'] = (
    theme2_features['HeartFailurePatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138

# ============================================================
# Feature 21: Kidney Disease Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 21

beneficiary[['BeneID', 'ChronicCond_KidneyDisease']].head()

      BeneID  ChronicCond_KidneyDisease
0  BENE11001                          1
1  BENE11002                          2
2  BENE11003                          2
3  BENE11004                          2
4  BENE11005                          2

In [ ]:
# Check the coding of the Kidney Disease chronic condition variable

beneficiary['ChronicCond_KidneyDisease'].value_counts()

ChronicCond_KidneyDisease
2    95277
1    43279
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Kidney Disease condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_KidneyDisease']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Kidney Disease patients for each provider

kidney_disease_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_KidneyDisease']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

kidney_disease_patient_percentage.rename(
    columns={
        'ChronicCond_KidneyDisease': 'KidneyDiseasePatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

kidney_disease_patient_percentage.head()

   Provider  KidneyDiseasePatientPercentage
0  PRV51001                       70.833333
1  PRV51003                       44.444444
2  PRV51004                       34.057971
3  PRV51005                       35.959596
4  PRV51007                       29.310345

In [ ]:
# Check for missing values

kidney_disease_patient_percentage.isnull().sum()

Provider                          0
KidneyDiseasePatientPercentage    0
dtype: int64

In [ ]:
# Verify that Kidney Disease percentages remain between 0% and 100%

kidney_disease_patient_percentage[
    'KidneyDiseasePatientPercentage'
].describe()

count    5410.000000
mean       40.559216
std        18.658108
min         0.000000
25%        32.894737
50%        39.260188
75%        48.387097
max       100.000000
Name: KidneyDiseasePatientPercentage, dtype: float64

In [ ]:
# Merge Feature 21 into Theme 2 dataset

theme2_features = theme2_features.merge(
    kidney_disease_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['KidneyDiseasePatientPercentage'] = (
    theme2_features['KidneyDiseasePatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345

# ============================================================
# Feature 22: Cancer Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 22

beneficiary[['BeneID', 'ChronicCond_Cancer']].head()

      BeneID  ChronicCond_Cancer
0  BENE11001                   2
1  BENE11002                   2
2  BENE11003                   2
3  BENE11004                   2
4  BENE11005                   2

In [ ]:
# Check the coding of the Cancer chronic condition variable

beneficiary['ChronicCond_Cancer'].value_counts()

ChronicCond_Cancer
2    121935
1     16621
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Cancer condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Cancer']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Cancer patients for each provider

cancer_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Cancer']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

cancer_patient_percentage.rename(
    columns={'ChronicCond_Cancer': 'CancerPatientPercentage'},
    inplace=True
)

In [ ]:
# Preview engineered feature

cancer_patient_percentage.head()

   Provider  CancerPatientPercentage
0  PRV51001                20.833333
1  PRV51003                 8.547009
2  PRV51004                11.594203
3  PRV51005                11.919192
4  PRV51007                10.344828

In [ ]:
# Check for missing values

cancer_patient_percentage.isnull().sum()

Provider                   0
CancerPatientPercentage    0
dtype: int64

In [ ]:
# Verify that Cancer percentages remain between 0% and 100%

cancer_patient_percentage['CancerPatientPercentage'].describe()

count    5410.000000
mean       14.870106
std        12.893411
min         0.000000
25%         8.695652
50%        13.852714
75%        18.600924
max       100.000000
Name: CancerPatientPercentage, dtype: float64

In [ ]:
# Merge Feature 22 into Theme 2 dataset

theme2_features = theme2_features.merge(
    cancer_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['CancerPatientPercentage'] = (
    theme2_features['CancerPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828

# ============================================================
# Feature 23: COPD Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 23

beneficiary[['BeneID', 'ChronicCond_ObstrPulmonary']].head()

      BeneID  ChronicCond_ObstrPulmonary
0  BENE11001                           2
1  BENE11002                           2
2  BENE11003                           2
3  BENE11004                           2
4  BENE11005                           1

In [ ]:
# Check the coding of the COPD chronic condition variable

beneficiary['ChronicCond_ObstrPulmonary'].value_counts()

ChronicCond_ObstrPulmonary
2    105697
1     32859
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge COPD condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_ObstrPulmonary']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of COPD patients for each provider

copd_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_ObstrPulmonary']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

copd_patient_percentage.rename(
    columns={
        'ChronicCond_ObstrPulmonary': 'COPDPatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

copd_patient_percentage.head()

   Provider  COPDPatientPercentage
0  PRV51001              37.500000
1  PRV51003              28.205128
2  PRV51004              26.811594
3  PRV51005              21.212121
4  PRV51007              20.689655

In [ ]:
# Check for missing values

copd_patient_percentage.isnull().sum()

Provider                 0
COPDPatientPercentage    0
dtype: int64

In [ ]:
# Verify one row per provider

copd_patient_percentage.shape

(5410, 2)

In [ ]:
# Merge Feature 23 into Theme 2 dataset

theme2_features = theme2_features.merge(
    copd_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['COPDPatientPercentage'] = (
    theme2_features['COPDPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655

# ============================================================
# Feature 24: Depression Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 24

beneficiary[['BeneID', 'ChronicCond_Depression']].head()

      BeneID  ChronicCond_Depression
0  BENE11001                       1
1  BENE11002                       2
2  BENE11003                       2
3  BENE11004                       2
4  BENE11005                       2

In [ ]:
# Check the coding of the Depression chronic condition variable

beneficiary['ChronicCond_Depression'].value_counts()

ChronicCond_Depression
2    89296
1    49260
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Depression condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Depression']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Depression patients for each provider

depression_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Depression']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

depression_patient_percentage.rename(
    columns={
        'ChronicCond_Depression': 'DepressionPatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

depression_patient_percentage.head()

   Provider  DepressionPatientPercentage
0  PRV51001                    37.500000
1  PRV51003                    40.170940
2  PRV51004                    43.478261
3  PRV51005                    37.171717
4  PRV51007                    36.206897

In [ ]:
# Check for missing values

depression_patient_percentage.isnull().sum()

Provider                       0
DepressionPatientPercentage    0
dtype: int64

In [ ]:
# Verify that Depression percentages remain between 0% and 100%

depression_patient_percentage[
    'DepressionPatientPercentage'
].describe()

count    5410.000000
mean       42.415870
std        17.699023
min         0.000000
25%        35.384615
50%        42.105263
75%        50.000000
max       100.000000
Name: DepressionPatientPercentage, dtype: float64

In [ ]:
# Merge Feature 24 into Theme 2 dataset

theme2_features = theme2_features.merge(
    depression_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897

# ============================================================
# Feature 25: Diabetes Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 25

beneficiary[['BeneID', 'ChronicCond_Diabetes']].head()

      BeneID  ChronicCond_Diabetes
0  BENE11001                     1
1  BENE11002                     2
2  BENE11003                     2
3  BENE11004                     1
4  BENE11005                     1

In [ ]:
# Check the coding of the Diabetes chronic condition variable

beneficiary['ChronicCond_Diabetes'].value_counts()

ChronicCond_Diabetes
1    83391
2    55165
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Diabetes condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Diabetes']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Diabetes patients for each provider

diabetes_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Diabetes']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

diabetes_patient_percentage.rename(
    columns={
        'ChronicCond_Diabetes': 'DiabetesPatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

diabetes_patient_percentage.head()

   Provider  DiabetesPatientPercentage
0  PRV51001                  83.333333
1  PRV51003                  74.358974
2  PRV51004                  69.565217
3  PRV51005                  63.434343
4  PRV51007                  62.068966

In [ ]:
# Check for missing values

diabetes_patient_percentage.isnull().sum()

Provider                     0
DiabetesPatientPercentage    0
dtype: int64

In [ ]:
# Merge Feature 25 into Theme 2 dataset

theme2_features = theme2_features.merge(
    diabetes_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['DiabetesPatientPercentage'] = (
    theme2_features['DiabetesPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966

# ============================================================
# Feature 26: Ischemic Heart Disease Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 26

beneficiary[['BeneID', 'ChronicCond_IschemicHeart']].head()

      BeneID  ChronicCond_IschemicHeart
0  BENE11001                          1
1  BENE11002                          2
2  BENE11003                          1
3  BENE11004                          1
4  BENE11005                          2

In [ ]:
# Check the coding of the Ischemic Heart Disease chronic condition variable

beneficiary['ChronicCond_IschemicHeart'].value_counts()

ChronicCond_IschemicHeart
1    93644
2    44912
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Ischemic Heart Disease condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_IschemicHeart']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Ischemic Heart Disease patients for each provider

ischemic_heart_disease_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_IschemicHeart']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

ischemic_heart_disease_percentage.rename(
    columns={
        'ChronicCond_IschemicHeart': 'IschemicHeartDiseasePercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

ischemic_heart_disease_percentage.head()

   Provider  IschemicHeartDiseasePercentage
0  PRV51001                       91.666667
1  PRV51003                       84.615385
2  PRV51004                       71.014493
3  PRV51005                       70.101010
4  PRV51007                       68.965517

In [ ]:
# Check for missing values

ischemic_heart_disease_percentage.isnull().sum()

Provider                          0
IschemicHeartDiseasePercentage    0
dtype: int64

In [ ]:
# Merge Feature 26 into Theme 2 dataset

theme2_features = theme2_features.merge(
    ischemic_heart_disease_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['IschemicHeartDiseasePercentage'] = (
    theme2_features['IschemicHeartDiseasePercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517

# ============================================================
# Feature 27: Osteoporosis Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 27

beneficiary[['BeneID', 'ChronicCond_Osteoporasis']].head()

      BeneID  ChronicCond_Osteoporasis
0  BENE11001                         2
1  BENE11002                         2
2  BENE11003                         2
3  BENE11004                         1
4  BENE11005                         2

In [ ]:
# Check the coding of the Osteoporosis chronic condition variable

beneficiary['ChronicCond_Osteoporasis'].value_counts()

ChronicCond_Osteoporasis
2    100497
1     38059
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Osteoporosis condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_Osteoporasis']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Osteoporosis patients for each provider

osteoporosis_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_Osteoporasis']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

osteoporosis_patient_percentage.rename(
    columns={
        'ChronicCond_Osteoporasis': 'OsteoporosisPatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

osteoporosis_patient_percentage.head()

   Provider  OsteoporosisPatientPercentage
0  PRV51001                      25.000000
1  PRV51003                      23.931624
2  PRV51004                      31.159420
3  PRV51005                      28.686869
4  PRV51007                      29.310345

In [ ]:
# Check for missing values

osteoporosis_patient_percentage.isnull().sum()

Provider                         0
OsteoporosisPatientPercentage    0
dtype: int64

In [ ]:
# Merge Feature 27 into Theme 2 dataset

theme2_features = theme2_features.merge(
    osteoporosis_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['OsteoporosisPatientPercentage'] = (
    theme2_features['OsteoporosisPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345

# ============================================================
# Feature 28: Rheumatoid Arthritis Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 28

beneficiary[['BeneID', 'ChronicCond_rheumatoidarthritis']].head()

      BeneID  ChronicCond_rheumatoidarthritis
0  BENE11001                                1
1  BENE11002                                2
2  BENE11003                                2
3  BENE11004                                1
4  BENE11005                                2

In [ ]:
# Check the coding of the Rheumatoid Arthritis chronic condition variable

beneficiary['ChronicCond_rheumatoidarthritis'].value_counts()

ChronicCond_rheumatoidarthritis
2    102972
1     35584
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Rheumatoid Arthritis condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_rheumatoidarthritis']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Rheumatoid Arthritis patients for each provider

rheumatoid_arthritis_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_rheumatoidarthritis']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

rheumatoid_arthritis_patient_percentage.rename(
    columns={
        'ChronicCond_rheumatoidarthritis':
        'RheumatoidArthritisPatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

rheumatoid_arthritis_patient_percentage.head()

   Provider  RheumatoidArthritisPatientPercentage
0  PRV51001                             33.333333
1  PRV51003                             27.350427
2  PRV51004                             29.710145
3  PRV51005                             25.656566
4  PRV51007                             27.586207

In [ ]:
# Check for missing values

rheumatoid_arthritis_patient_percentage.isnull().sum()

Provider                                0
RheumatoidArthritisPatientPercentage    0
dtype: int64

In [ ]:
# Merge Feature 28 into Theme 2 dataset

theme2_features = theme2_features.merge(
    rheumatoid_arthritis_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['RheumatoidArthritisPatientPercentage'] = (
    theme2_features['RheumatoidArthritisPatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000,33.333333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624,27.350427
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420,29.710145
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869,25.656566
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345,27.586207

# ============================================================
# Feature 29: Stroke Patient Percentage
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 29

beneficiary[['BeneID', 'ChronicCond_stroke']].head()

      BeneID  ChronicCond_stroke
0  BENE11001                   1
1  BENE11002                   2
2  BENE11003                   2
3  BENE11004                   2
4  BENE11005                   2

In [ ]:
# Check the coding of the Stroke chronic condition variable

beneficiary['ChronicCond_stroke'].value_counts()

ChronicCond_stroke
2    127602
1     10954
Name: count, dtype: int64

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge Stroke condition into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'ChronicCond_stroke']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the percentage of Stroke patients for each provider

stroke_patient_percentage = (
    provider_bene_temp
    .groupby('Provider')['ChronicCond_stroke']
    .apply(lambda x: (x == 1).mean() * 100)
    .reset_index()
)

stroke_patient_percentage.rename(
    columns={
        'ChronicCond_stroke': 'StrokePatientPercentage'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

stroke_patient_percentage.head()

   Provider  StrokePatientPercentage
0  PRV51001                20.833333
1  PRV51003                 7.692308
2  PRV51004                11.594203
3  PRV51005                 7.878788
4  PRV51007                15.517241

In [ ]:
# Check for missing values

stroke_patient_percentage.isnull().sum()

Provider                   0
StrokePatientPercentage    0
dtype: int64

In [ ]:
# Merge Feature 29 into Theme 2 dataset

theme2_features = theme2_features.merge(
    stroke_patient_percentage,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['StrokePatientPercentage'] = (
    theme2_features['StrokePatientPercentage']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000,33.333333,20.833333
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624,27.350427,7.692308
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420,29.710145,11.594203
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869,25.656566,7.878788
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345,27.586207,15.517241

# ============================================================
# Feature 30: Average Annual Inpatient Reimbursement
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 30

beneficiary[['BeneID', 'IPAnnualReimbursementAmt']].head()

      BeneID  IPAnnualReimbursementAmt
0  BENE11001                     36000
1  BENE11002                         0
2  BENE11003                         0
3  BENE11004                         0
4  BENE11005                         0

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge annual inpatient reimbursement into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'IPAnnualReimbursementAmt']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average annual inpatient reimbursement for each provider

average_annual_inpatient_reimbursement = (
    provider_bene_temp
    .groupby('Provider')['IPAnnualReimbursementAmt']
    .mean()
    .reset_index()
)

average_annual_inpatient_reimbursement.rename(
    columns={
        'IPAnnualReimbursementAmt':
        'AverageAnnualInpatientReimbursement'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

average_annual_inpatient_reimbursement.head()

   Provider  AverageAnnualInpatientReimbursement
0  PRV51001                         18047.916667
1  PRV51003                          6814.017094
2  PRV51004                          4596.739130
3  PRV51005                          3717.232323
4  PRV51007                          3109.655172

In [ ]:
# Check for missing values

average_annual_inpatient_reimbursement.isnull().sum()

Provider                               0
AverageAnnualInpatientReimbursement    0
dtype: int64

In [ ]:
# Merge Feature 30 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_annual_inpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AverageAnnualInpatientReimbursement'] = (
    theme2_features['AverageAnnualInpatientReimbursement']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000,33.333333,20.833333,18047.916667
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624,27.350427,7.692308,6814.017094
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420,29.710145,11.594203,4596.739130
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869,25.656566,7.878788,3717.232323
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345,27.586207,15.517241,3109.655172

# ============================================================
# Feature 31: Average Annual Outpatient Reimbursement
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 31

beneficiary[['BeneID', 'OPAnnualReimbursementAmt']].head()

      BeneID  OPAnnualReimbursementAmt
0  BENE11001                        60
1  BENE11002                        30
2  BENE11003                        90
3  BENE11004                      1810
4  BENE11005                      1790

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge annual outpatient reimbursement into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'OPAnnualReimbursementAmt']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average annual outpatient reimbursement for each provider

average_annual_outpatient_reimbursement = (
    provider_bene_temp
    .groupby('Provider')['OPAnnualReimbursementAmt']
    .mean()
    .reset_index()
)

average_annual_outpatient_reimbursement.rename(
    columns={
        'OPAnnualReimbursementAmt':
        'AverageAnnualOutpatientReimbursement'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

average_annual_outpatient_reimbursement.head()

   Provider  AverageAnnualOutpatientReimbursement
0  PRV51001                           2537.500000
1  PRV51003                           2490.598291
2  PRV51004                           2095.144928
3  PRV51005                           1798.808081
4  PRV51007                           1497.241379

In [ ]:
# Check for missing values

average_annual_outpatient_reimbursement.isnull().sum()

Provider                                0
AverageAnnualOutpatientReimbursement    0
dtype: int64

In [ ]:
# Merge Feature 31 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_annual_outpatient_reimbursement,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AverageAnnualOutpatientReimbursement'] = (
    theme2_features['AverageAnnualOutpatientReimbursement']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000,33.333333,20.833333,18047.916667,2537.500000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624,27.350427,7.692308,6814.017094,2490.598291
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420,29.710145,11.594203,4596.739130,2095.144928
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869,25.656566,7.878788,3717.232323,1798.808081
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345,27.586207,15.517241,3109.655172,1497.241379

# ============================================================
# Feature 32: Average Annual Inpatient Deductible
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 32

beneficiary[['BeneID', 'IPAnnualDeductibleAmt']].head()

      BeneID  IPAnnualDeductibleAmt
0  BENE11001                   3204
1  BENE11002                      0
2  BENE11003                      0
3  BENE11004                      0
4  BENE11005                      0

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge annual inpatient deductible into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'IPAnnualDeductibleAmt']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average annual inpatient deductible for each provider

average_annual_inpatient_deductible = (
    provider_bene_temp
    .groupby('Provider')['IPAnnualDeductibleAmt']
    .mean()
    .reset_index()
)

average_annual_inpatient_deductible.rename(
    columns={
        'IPAnnualDeductibleAmt':
        'AverageAnnualInpatientDeductible'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

average_annual_inpatient_deductible.head()

   Provider  AverageAnnualInpatientDeductible
0  PRV51001                        890.000000
1  PRV51003                        822.632479
2  PRV51004                        454.144928
3  PRV51005                        398.698990
4  PRV51007                        423.517241

In [ ]:
# Check for missing values

average_annual_inpatient_deductible.isnull().sum()

Provider                            0
AverageAnnualInpatientDeductible    0
dtype: int64

In [ ]:
# Merge Feature 32 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_annual_inpatient_deductible,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AverageAnnualInpatientDeductible'] = (
    theme2_features['AverageAnnualInpatientDeductible']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,COPDPatientPercentage,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,37.500000,37.500000,83.333333,91.666667,25.000000,33.333333,20.833333,18047.916667,2537.500000,890.000000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,28.205128,40.170940,74.358974,84.615385,23.931624,27.350427,7.692308,6814.017094,2490.598291,822.632479
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,26.811594,43.478261,69.565217,71.014493,31.159420,29.710145,11.594203,4596.739130,2095.144928,454.144928
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,21.212121,37.171717,63.434343,70.101010,28.686869,25.656566,7.878788,3717.232323,1798.808081,398.698990
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,20.689655,36.206897,62.068966,68.965517,29.310345,27.586207,15.517241,3109.655172,1497.241379,423.517241

# ============================================================
# Feature 33: Average Annual Outpatient Deductible
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables for Feature 33

beneficiary[['BeneID', 'OPAnnualDeductibleAmt']].head()

      BeneID  OPAnnualDeductibleAmt
0  BENE11001                     70
1  BENE11002                     50
2  BENE11003                     40
3  BENE11004                    760
4  BENE11005                   1200

In [ ]:
# Display provider-beneficiary relationships from inpatient claims

inpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV55912  BENE11001
1  PRV55907  BENE11001
2  PRV56046  BENE11001
3  PRV52405  BENE11011
4  PRV56614  BENE11014

In [ ]:
# Display provider-beneficiary relationships from outpatient claims

outpatient[['Provider', 'BeneID']].head()

   Provider     BeneID
0  PRV56011  BENE11002
1  PRV57610  BENE11003
2  PRV57595  BENE11003
3  PRV56011  BENE11004
4  PRV56011  BENE11004

In [ ]:
# Combine provider-beneficiary relationships from inpatient and outpatient claims

provider_bene_temp = pd.concat([
    inpatient[['Provider', 'BeneID']],
    outpatient[['Provider', 'BeneID']]
], ignore_index=True)

In [ ]:
# Keep one record for each unique provider-beneficiary combination

provider_bene_temp = provider_bene_temp.drop_duplicates()

In [ ]:
# Merge annual outpatient deductible into provider-beneficiary table

provider_bene_temp = provider_bene_temp.merge(
    beneficiary[['BeneID', 'OPAnnualDeductibleAmt']],
    on='BeneID',
    how='left'
)

In [ ]:
# Calculate the average annual outpatient deductible for each provider

average_annual_outpatient_deductible = (
    provider_bene_temp
    .groupby('Provider')['OPAnnualDeductibleAmt']
    .mean()
    .reset_index()
)

average_annual_outpatient_deductible.rename(
    columns={
        'OPAnnualDeductibleAmt':
        'AverageAnnualOutpatientDeductible'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

average_annual_outpatient_deductible.head()

   Provider  AverageAnnualOutpatientDeductible
0  PRV51001                         474.916667
1  PRV51003                         664.529915
2  PRV51004                         600.869565
3  PRV51005                         475.965657
4  PRV51007                         430.689655

In [ ]:
# Check for missing values

average_annual_outpatient_deductible.isnull().sum()

Provider                             0
AverageAnnualOutpatientDeductible    0
dtype: int64

In [ ]:
# Merge Feature 33 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_annual_outpatient_deductible,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['AverageAnnualOutpatientDeductible'] = (
    theme2_features['AverageAnnualOutpatientDeductible']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,DepressionPatientPercentage,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,37.500000,83.333333,91.666667,25.000000,33.333333,20.833333,18047.916667,2537.500000,890.000000,474.916667
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,40.170940,74.358974,84.615385,23.931624,27.350427,7.692308,6814.017094,2490.598291,822.632479,664.529915
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,43.478261,69.565217,71.014493,31.159420,29.710145,11.594203,4596.739130,2095.144928,454.144928,600.869565
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,37.171717,63.434343,70.101010,28.686869,25.656566,7.878788,3717.232323,1798.808081,398.698990,475.965657
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,36.206897,62.068966,68.965517,29.310345,27.586207,15.517241,3109.655172,1497.241379,423.517241,430.689655

# ============================================================
# Feature 34: Average Deductible Paid Per Claim
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables from inpatient claims

inpatient[['Provider', 'DeductibleAmtPaid']].head()

   Provider  DeductibleAmtPaid
0  PRV55912             1068.0
1  PRV55907             1068.0
2  PRV56046             1068.0
3  PRV52405             1068.0
4  PRV56614             1068.0

In [ ]:
# Display required variables from outpatient claims

outpatient[['Provider', 'DeductibleAmtPaid']].head()

   Provider  DeductibleAmtPaid
0  PRV56011                  0
1  PRV57610                  0
2  PRV57595                  0
3  PRV56011                  0
4  PRV56011                  0

In [ ]:
# Combine deductible amounts from inpatient and outpatient claims

deductible_paid_temp = pd.concat([
    inpatient[['Provider', 'DeductibleAmtPaid']],
    outpatient[['Provider', 'DeductibleAmtPaid']]
], ignore_index=True)# Review missing deductible values before aggregation

In [ ]:
# Review missing deductible values before aggregation

deductible_paid_temp['DeductibleAmtPaid'].isnull().sum()

np.int64(899)

In [ ]:
# Calculate the average deductible paid per claim for each provider

average_deductible_paid_per_claim = (
    deductible_paid_temp
    .groupby('Provider')['DeductibleAmtPaid']
    .mean()
    .reset_index()
)

average_deductible_paid_per_claim.rename(
    columns={
        'DeductibleAmtPaid': 'AverageDeductiblePaidPerClaim'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

average_deductible_paid_per_claim.head()

   Provider  AverageDeductiblePaidPerClaim
0  PRV51001                     213.600000
1  PRV51003                     502.166667
2  PRV51004                       2.080537
3  PRV51005                       3.175966
4  PRV51007                      45.333333

In [ ]:
# Check for missing values

average_deductible_paid_per_claim.isnull().sum()

Provider                         0
AverageDeductiblePaidPerClaim    1
dtype: int64

In [ ]:
# Review the distribution of the engineered feature

average_deductible_paid_per_claim[
    'AverageDeductiblePaidPerClaim'
].describe()

count    5409.000000
mean      155.643175
std       306.489453
min         0.000000
25%         0.312500
50%         4.285714
75%       137.418605
max      1068.000000
Name: AverageDeductiblePaidPerClaim, dtype: float64

In [ ]:
# Merge Feature 34 into Theme 2 dataset

theme2_features = theme2_features.merge(
    average_deductible_paid_per_claim,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing provider-level values with zero if necessary

theme2_features['AverageDeductiblePaidPerClaim'] = (
    theme2_features['AverageDeductiblePaidPerClaim']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,DiabetesPatientPercentage,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,83.333333,91.666667,25.000000,33.333333,20.833333,18047.916667,2537.500000,890.000000,474.916667,213.600000
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,74.358974,84.615385,23.931624,27.350427,7.692308,6814.017094,2490.598291,822.632479,664.529915,502.166667
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,69.565217,71.014493,31.159420,29.710145,11.594203,4596.739130,2095.144928,454.144928,600.869565,2.080537
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,63.434343,70.101010,28.686869,25.656566,7.878788,3717.232323,1798.808081,398.698990,475.965657,3.175966
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,62.068966,68.965517,29.310345,27.586207,15.517241,3109.655172,1497.241379,423.517241,430.689655,45.333333

# ============================================================
# Feature 35: Number of Unique Diagnosis Codes
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display diagnosis code variables from inpatient claims

inpatient[
    [
        'Provider',
        'ClmDiagnosisCode_1',
        'ClmDiagnosisCode_2',
        'ClmDiagnosisCode_3',
        'ClmDiagnosisCode_4',
        'ClmDiagnosisCode_5',
        'ClmDiagnosisCode_6',
        'ClmDiagnosisCode_7',
        'ClmDiagnosisCode_8',
        'ClmDiagnosisCode_9',
        'ClmDiagnosisCode_10'
    ]
].head()

,Provider,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10
0,PRV55912,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN
1,PRV55907,6186,2948,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PRV56046,29623,30390,71690,34590,V1581,32723,NaN,NaN,NaN,NaN
3,PRV52405,43491,2762,7843,32723,V1041,4254,25062,40390,4019,NaN
4,PRV56614,042,3051,34400,5856,42732,486,5119,29620,20300,NaN

In [ ]:
# Display diagnosis code variables from outpatient claims

outpatient[
    [
        'Provider',
        'ClmDiagnosisCode_1',
        'ClmDiagnosisCode_2',
        'ClmDiagnosisCode_3',
        'ClmDiagnosisCode_4',
        'ClmDiagnosisCode_5',
        'ClmDiagnosisCode_6',
        'ClmDiagnosisCode_7',
        'ClmDiagnosisCode_8',
        'ClmDiagnosisCode_9',
        'ClmDiagnosisCode_10'
    ]
].head()

,Provider,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10
0,PRV56011,78943,V5866,V1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PRV57610,6115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PRV57595,2723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PRV56011,71988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PRV56011,82382,30000,72887,4280,7197,V4577,NaN,NaN,NaN,NaN

In [ ]:
# Combine diagnosis codes from inpatient and outpatient claims

diagnosis_codes_temp = pd.concat([
    inpatient,
    outpatient
], ignore_index=True)

In [ ]:
# Convert diagnosis code columns into a long format

diagnosis_codes_temp = diagnosis_codes_temp.melt(
    id_vars='Provider',
    value_vars=[
        'ClmDiagnosisCode_1',
        'ClmDiagnosisCode_2',
        'ClmDiagnosisCode_3',
        'ClmDiagnosisCode_4',
        'ClmDiagnosisCode_5',
        'ClmDiagnosisCode_6',
        'ClmDiagnosisCode_7',
        'ClmDiagnosisCode_8',
        'ClmDiagnosisCode_9',
        'ClmDiagnosisCode_10'
    ],
    value_name='DiagnosisCode'
)

In [ ]:
# Remove missing diagnosis codes

diagnosis_codes_temp = diagnosis_codes_temp.dropna(
    subset=['DiagnosisCode']
)

In [ ]:
# Calculate the number of unique diagnosis codes for each provider

number_of_unique_diagnosis_codes = (
    diagnosis_codes_temp
    .groupby('Provider')['DiagnosisCode']
    .nunique()
    .reset_index()
)

number_of_unique_diagnosis_codes.rename(
    columns={
        'DiagnosisCode': 'NumberOfUniqueDiagnosisCodes'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

number_of_unique_diagnosis_codes.head()

   Provider  NumberOfUniqueDiagnosisCodes
0  PRV51001                            72
1  PRV51003                           365
2  PRV51004                           267
3  PRV51005                          1294
4  PRV51007                           165

In [ ]:
# Check for missing values

number_of_unique_diagnosis_codes.isnull().sum()

Provider                        0
NumberOfUniqueDiagnosisCodes    0
dtype: int64

In [ ]:
# Merge Feature 35 into Theme 2 dataset

theme2_features = theme2_features.merge(
    number_of_unique_diagnosis_codes,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['NumberOfUniqueDiagnosisCodes'] = (
    theme2_features['NumberOfUniqueDiagnosisCodes']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,IschemicHeartDiseasePercentage,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,91.666667,25.000000,33.333333,20.833333,18047.916667,2537.500000,890.000000,474.916667,213.600000,72.0
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,84.615385,23.931624,27.350427,7.692308,6814.017094,2490.598291,822.632479,664.529915,502.166667,365.0
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,71.014493,31.159420,29.710145,11.594203,4596.739130,2095.144928,454.144928,600.869565,2.080537,267.0
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,70.101010,28.686869,25.656566,7.878788,3717.232323,1798.808081,398.698990,475.965657,3.175966,1294.0
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,68.965517,29.310345,27.586207,15.517241,3109.655172,1497.241379,423.517241,430.689655,45.333333,165.0

# ============================================================
# Feature 36: Number of Unique Procedure Codes
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display procedure code variables from inpatient claims

inpatient[
    [
        'Provider',
        'ClmProcedureCode_1',
        'ClmProcedureCode_2',
        'ClmProcedureCode_3',
        'ClmProcedureCode_4',
        'ClmProcedureCode_5',
        'ClmProcedureCode_6'
    ]
].head()

,Provider,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,PRV55912,NaN,NaN,NaN,NaN,NaN,NaN
1,PRV55907,7092.0,NaN,NaN,NaN,NaN,NaN
2,PRV56046,NaN,NaN,NaN,NaN,NaN,NaN
3,PRV52405,331.0,NaN,NaN,NaN,NaN,NaN
4,PRV56614,3893.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Display procedure code variables from outpatient claims

outpatient[
    [
        'Provider',
        'ClmProcedureCode_1',
        'ClmProcedureCode_2',
        'ClmProcedureCode_3',
        'ClmProcedureCode_4',
        'ClmProcedureCode_5',
        'ClmProcedureCode_6'
    ]
].head()

,Provider,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,PRV56011,NaN,NaN,NaN,NaN,NaN,NaN
1,PRV57610,NaN,NaN,NaN,NaN,NaN,NaN
2,PRV57595,NaN,NaN,NaN,NaN,NaN,NaN
3,PRV56011,NaN,NaN,NaN,NaN,NaN,NaN
4,PRV56011,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Combine procedure codes from inpatient and outpatient claims

procedure_codes_temp = pd.concat([
    inpatient,
    outpatient
], ignore_index=True)

In [ ]:
# Convert procedure code columns into a long format

procedure_codes_temp = procedure_codes_temp.melt(
    id_vars='Provider',
    value_vars=[
        'ClmProcedureCode_1',
        'ClmProcedureCode_2',
        'ClmProcedureCode_3',
        'ClmProcedureCode_4',
        'ClmProcedureCode_5',
        'ClmProcedureCode_6'
    ],
    value_name='ProcedureCode'
)

In [ ]:
# Remove missing procedure codes

procedure_codes_temp = procedure_codes_temp.dropna(
    subset=['ProcedureCode']
)

In [ ]:
# Calculate the number of unique procedure codes for each provider

number_of_unique_procedure_codes = (
    procedure_codes_temp
    .groupby('Provider')['ProcedureCode']
    .nunique()
    .reset_index()
)

number_of_unique_procedure_codes.rename(
    columns={
        'ProcedureCode': 'NumberOfUniqueProcedureCodes'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

number_of_unique_procedure_codes.head()

   Provider  NumberOfUniqueProcedureCodes
0  PRV51001                             3
1  PRV51003                            39
2  PRV51007                             1
3  PRV51008                             2
4  PRV51017                             2

In [ ]:
# Check for missing values

number_of_unique_procedure_codes.isnull().sum()

Provider                        0
NumberOfUniqueProcedureCodes    0
dtype: int64

In [ ]:
# Merge Feature 36 into Theme 2 dataset

theme2_features = theme2_features.merge(
    number_of_unique_procedure_codes,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['NumberOfUniqueProcedureCodes'] = (
    theme2_features['NumberOfUniqueProcedureCodes']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,OsteoporosisPatientPercentage,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,25.000000,33.333333,20.833333,18047.916667,2537.500000,890.000000,474.916667,213.600000,72.0,3.0
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,23.931624,27.350427,7.692308,6814.017094,2490.598291,822.632479,664.529915,502.166667,365.0,39.0
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,31.159420,29.710145,11.594203,4596.739130,2095.144928,454.144928,600.869565,2.080537,267.0,0.0
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,28.686869,25.656566,7.878788,3717.232323,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,29.310345,27.586207,15.517241,3109.655172,1497.241379,423.517241,430.689655,45.333333,165.0,1.0

# ============================================================
# Feature 37: Number of Unique Attending Physicians
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables from inpatient claims

inpatient[['Provider', 'AttendingPhysician']].head()

   Provider AttendingPhysician
0  PRV55912          PHY390922
1  PRV55907          PHY318495
2  PRV56046          PHY372395
3  PRV52405          PHY369659
4  PRV56614          PHY379376

In [ ]:
# Display required variables from outpatient claims

outpatient[['Provider', 'AttendingPhysician']].head()

   Provider AttendingPhysician
0  PRV56011          PHY326117
1  PRV57610          PHY362868
2  PRV57595          PHY328821
3  PRV56011          PHY334319
4  PRV56011          PHY403831

In [ ]:
# Combine attending physician information from inpatient and outpatient claims

attending_physician_temp = pd.concat([
    inpatient[['Provider', 'AttendingPhysician']],
    outpatient[['Provider', 'AttendingPhysician']]
], ignore_index=True)

In [ ]:
# Remove missing attending physician values

attending_physician_temp = attending_physician_temp.dropna(
    subset=['AttendingPhysician']
)

In [ ]:
# Calculate the number of unique attending physicians for each provider

number_of_unique_attending_physicians = (
    attending_physician_temp
    .groupby('Provider')['AttendingPhysician']
    .nunique()
    .reset_index()
)

number_of_unique_attending_physicians.rename(
    columns={
        'AttendingPhysician':
        'NumberOfUniqueAttendingPhysicians'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

number_of_unique_attending_physicians.head()

   Provider  NumberOfUniqueAttendingPhysicians
0  PRV51001                                 14
1  PRV51003                                 44
2  PRV51004                                 38
3  PRV51005                                  6
4  PRV51007                                 10

In [ ]:
# Check for missing values

number_of_unique_attending_physicians.isnull().sum()

Provider                             0
NumberOfUniqueAttendingPhysicians    0
dtype: int64

In [ ]:
# Merge Feature 37 into Theme 2 dataset

theme2_features = theme2_features.merge(
    number_of_unique_attending_physicians,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['NumberOfUniqueAttendingPhysicians'] = (
    theme2_features['NumberOfUniqueAttendingPhysicians']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,RheumatoidArthritisPatientPercentage,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes,NumberOfUniqueAttendingPhysicians
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,33.333333,20.833333,18047.916667,2537.500000,890.000000,474.916667,213.600000,72.0,3.0,14
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,27.350427,7.692308,6814.017094,2490.598291,822.632479,664.529915,502.166667,365.0,39.0,44
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,29.710145,11.594203,4596.739130,2095.144928,454.144928,600.869565,2.080537,267.0,0.0,38
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,25.656566,7.878788,3717.232323,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0,6
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,27.586207,15.517241,3109.655172,1497.241379,423.517241,430.689655,45.333333,165.0,1.0,10

# ============================================================
# Feature 38: Number of Unique Operating Physicians
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables from inpatient claims

inpatient[['Provider', 'OperatingPhysician']].head()

   Provider OperatingPhysician
0  PRV55912                NaN
1  PRV55907          PHY318495
2  PRV56046                NaN
3  PRV52405          PHY392961
4  PRV56614          PHY398258

In [ ]:
# Display required variables from outpatient claims

outpatient[['Provider', 'OperatingPhysician']].head()

   Provider OperatingPhysician
0  PRV56011                NaN
1  PRV57610                NaN
2  PRV57595                NaN
3  PRV56011                NaN
4  PRV56011                NaN

In [ ]:
outpatient['OperatingPhysician'].value_counts(dropna=False)

OperatingPhysician
NaN          427120
PHY330576       424
PHY424897       293
PHY314027       256
PHY423534       250
              ...
PHY403068         1
PHY425118         1
PHY318265         1
PHY361170         1
PHY369758         1
Name: count, Length: 28533, dtype: int64

In [ ]:
# Combine operating physician information from inpatient and outpatient claims

operating_physician_temp = pd.concat([
    inpatient[['Provider', 'OperatingPhysician']],
    outpatient[['Provider', 'OperatingPhysician']]
], ignore_index=True)

In [ ]:
# Remove missing operating physician values

operating_physician_temp = operating_physician_temp.dropna(
    subset=['OperatingPhysician']
)

In [ ]:
# Calculate the number of unique operating physicians for each provider

number_of_unique_operating_physicians = (
    operating_physician_temp
    .groupby('Provider')['OperatingPhysician']
    .nunique()
    .reset_index()
)

number_of_unique_operating_physicians.rename(
    columns={
        'OperatingPhysician':
        'NumberOfUniqueOperatingPhysicians'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

number_of_unique_operating_physicians.head()

   Provider  NumberOfUniqueOperatingPhysicians
0  PRV51001                                  5
1  PRV51003                                  7
2  PRV51004                                 19
3  PRV51005                                  6
4  PRV51007                                  5

In [ ]:
# Check for missing values

number_of_unique_operating_physicians.isnull().sum()

Provider                             0
NumberOfUniqueOperatingPhysicians    0
dtype: int64

In [ ]:
# Merge Feature 38 into Theme 2 dataset

theme2_features = theme2_features.merge(
    number_of_unique_operating_physicians,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['NumberOfUniqueOperatingPhysicians'] = (
    theme2_features['NumberOfUniqueOperatingPhysicians']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,StrokePatientPercentage,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes,NumberOfUniqueAttendingPhysicians,NumberOfUniqueOperatingPhysicians
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,20.833333,18047.916667,2537.500000,890.000000,474.916667,213.600000,72.0,3.0,14,5.0
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,7.692308,6814.017094,2490.598291,822.632479,664.529915,502.166667,365.0,39.0,44,7.0
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,11.594203,4596.739130,2095.144928,454.144928,600.869565,2.080537,267.0,0.0,38,19.0
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,7.878788,3717.232323,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0,6,6.0
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,15.517241,3109.655172,1497.241379,423.517241,430.689655,45.333333,165.0,1.0,10,5.0

# ============================================================
# Feature 39: Number of Unique Other Physicians
# Theme 2: Medical Complexity and Billing Pattern
# ============================================================

In [ ]:
# Display required variables from inpatient claims

inpatient[['Provider', 'OtherPhysician']].head()

   Provider OtherPhysician
0  PRV55912            NaN
1  PRV55907            NaN
2  PRV56046      PHY324689
3  PRV52405      PHY349768
4  PRV56614            NaN

In [ ]:
# Display required variables from outpatient claims

outpatient[['Provider', 'OtherPhysician']].head()

   Provider OtherPhysician
0  PRV56011            NaN
1  PRV57610            NaN
2  PRV57595            NaN
3  PRV56011            NaN
4  PRV56011            NaN

In [ ]:
# Combine other physician information from inpatient and outpatient claims

other_physician_temp = pd.concat([
    inpatient[['Provider', 'OtherPhysician']],
    outpatient[['Provider', 'OtherPhysician']]
], ignore_index=True)

In [ ]:
# Remove missing other physician values

other_physician_temp = other_physician_temp.dropna(
    subset=['OtherPhysician']
)

In [ ]:
# Calculate the number of unique other physicians for each provider

number_of_unique_other_physicians = (
    other_physician_temp
    .groupby('Provider')['OtherPhysician']
    .nunique()
    .reset_index()
)

number_of_unique_other_physicians.rename(
    columns={
        'OtherPhysician':
        'NumberOfUniqueOtherPhysicians'
    },
    inplace=True
)

In [ ]:
# Preview engineered feature

number_of_unique_other_physicians.head()

   Provider  NumberOfUniqueOtherPhysicians
0  PRV51001                              8
1  PRV51003                             22
2  PRV51004                             26
3  PRV51005                              4
4  PRV51007                              7

In [ ]:
# Check for missing values

number_of_unique_other_physicians.isnull().sum()

Provider                         0
NumberOfUniqueOtherPhysicians    0
dtype: int64

In [ ]:
# Merge Feature 39 into Theme 2 dataset

theme2_features = theme2_features.merge(
    number_of_unique_other_physicians,
    on='Provider',
    how='left'
)

In [ ]:
# Replace missing values with zero if necessary

theme2_features['NumberOfUniqueOtherPhysicians'] = (
    theme2_features['NumberOfUniqueOtherPhysicians']
    .fillna(0)
)

In [ ]:
# Preview Theme 2 dataset

theme2_features.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,AverageAnnualInpatientReimbursement,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes,NumberOfUniqueAttendingPhysicians,NumberOfUniqueOperatingPhysicians,NumberOfUniqueOtherPhysicians
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,18047.916667,2537.500000,890.000000,474.916667,213.600000,72.0,3.0,14,5.0,8.0
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,6814.017094,2490.598291,822.632479,664.529915,502.166667,365.0,39.0,44,7.0,22.0
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,4596.739130,2095.144928,454.144928,600.869565,2.080537,267.0,0.0,38,19.0,26.0
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,3717.232323,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0,6,6.0,4.0
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,3109.655172,1497.241379,423.517241,430.689655,45.333333,165.0,1.0,10,5.0,7.0

In [ ]:
# Merge Theme 1 and Theme 2 using Provider as the common key.

theme12_features = theme1_features.merge(
    theme2_features,
    on="Provider",
    how="inner"
)

In [ ]:
# Add the fraud label to the combined feature dataset.

theme12_features = theme12_features.merge(
    provider,
    on="Provider",
    how="left"
)

In [ ]:
theme12_features.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration,...,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes,NumberOfUniqueAttendingPhysicians,NumberOfUniqueOperatingPhysicians,NumberOfUniqueOtherPhysicians,PotentialFraud
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000,...,2537.500000,890.000000,474.916667,213.600000,72.0,3.0,14,5.0,8.0,No
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290,...,2490.598291,822.632479,664.529915,502.166667,365.0,39.0,44,7.0,22.0,Yes
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000,...,2095.144928,454.144928,600.869565,2.080537,267.0,0.0,38,19.0,26.0,No
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000,...,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0,6,6.0,4.0,Yes
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333,...,1497.241379,423.517241,430.689655,45.333333,165.0,1.0,10,5.0,7.0,No

In [ ]:
# Merge Theme 1 features with the provider fraud label.

theme1_final = theme1_features.merge(
    provider,
    on="Provider",
    how="left"
)

In [ ]:
# Preview the Theme 1 final dataset.

theme1_final.head()

,Provider,Total_Inpatient_Claims,Total_Outpatient_Claims,Total_Claims,Unique_Beneficiaries,Avg_Inpatient_Reimbursement,Avg_Outpatient_Reimbursement,Total_Inpatient_Reimbursement,Total_Outpatient_Reimbursement,Avg_Claim_Duration,Avg_Length_of_Stay,Inpatient_Outpatient_Ratio,Number_of_States_Served,Number_of_Counties_Served,PotentialFraud
0,PRV51001,5.0,20.0,25.0,24,19400.000000,382.000000,97000.0,7640.0,5.000000,5.000000,0.250000,1,7,No
1,PRV51003,62.0,70.0,132.0,117,9241.935484,466.714286,573000.0,32670.0,5.161290,5.161290,0.885714,3,23,Yes
2,PRV51004,0.0,149.0,149.0,138,0.000000,350.134228,0.0,52170.0,0.000000,0.000000,0.000000,9,28,No
3,PRV51005,0.0,1165.0,1165.0,495,0.000000,241.124464,0.0,280910.0,0.000000,0.000000,0.000000,4,26,Yes
4,PRV51007,3.0,69.0,72.0,58,6333.333333,213.188406,19000.0,14710.0,5.333333,5.333333,0.043478,2,6,No

In [ ]:
# Verify the dimensions of the Theme 1 final dataset.

print(theme1_final.shape)

(5410, 15)

In [ ]:
# Save the Theme 1 final dataset.

theme1_final.to_csv(
    "Theme1_Final.csv",
    index=False
)

In [ ]:
# Download the Theme 1 final dataset.

from google.colab import files

files.download("Theme1_Final.csv")

In [ ]:
# Merge Theme 2 features with the provider fraud label.

theme2_final = theme2_features.merge(
    provider,
    on="Provider",
    how="left"
)

In [ ]:
# Preview the Theme 2 final dataset.

theme2_final.head()

,Provider,AveragePatientAge,PercentageMalePatients,PercentageFemalePatients,AveragePartACoverage,AveragePartBCoverage,AlzheimerPatientPercentage,HeartFailurePatientPercentage,KidneyDiseasePatientPercentage,CancerPatientPercentage,...,AverageAnnualOutpatientReimbursement,AverageAnnualInpatientDeductible,AverageAnnualOutpatientDeductible,AverageDeductiblePaidPerClaim,NumberOfUniqueDiagnosisCodes,NumberOfUniqueProcedureCodes,NumberOfUniqueAttendingPhysicians,NumberOfUniqueOperatingPhysicians,NumberOfUniqueOtherPhysicians,PotentialFraud
0,PRV51001,78.208333,37.500000,62.500000,12.000000,12.000000,58.333333,75.000000,70.833333,20.833333,...,2537.500000,890.000000,474.916667,213.600000,72.0,3.0,14,5.0,8.0,No
1,PRV51003,69.051282,41.880342,58.119658,11.794872,11.854701,37.606838,59.829060,44.444444,8.547009,...,2490.598291,822.632479,664.529915,502.166667,365.0,39.0,44,7.0,22.0,Yes
2,PRV51004,72.557971,32.608696,67.391304,11.855072,11.956522,43.478261,59.420290,34.057971,11.594203,...,2095.144928,454.144928,600.869565,2.080537,267.0,0.0,38,19.0,26.0,No
3,PRV51005,70.070707,42.020202,57.979798,11.830303,11.886869,33.333333,53.131313,35.959596,11.919192,...,1798.808081,398.698990,475.965657,3.175966,1294.0,0.0,6,6.0,4.0,Yes
4,PRV51007,68.017241,46.551724,53.448276,11.793103,11.793103,36.206897,51.724138,29.310345,10.344828,...,1497.241379,423.517241,430.689655,45.333333,165.0,1.0,10,5.0,7.0,No

In [ ]:
# Verify the dimensions of the Theme 2 final dataset.

print(theme2_final.shape)

(5410, 28)

In [ ]:
# Save the Theme 2 final dataset.

theme2_final.to_csv(
    "Theme2_Final.csv",
    index=False
)

In [ ]:
# Download the Theme 2 final dataset.

from google.colab import files

files.download("Theme2_Final.csv")